### ISSUE TITLE
JSV/Parameters: Nullable is a type not a validation

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1017]
## Describe the bug

The new design of JSV/Parameters has `Nullable` showing up with a validation badge like greater/less than, but really it should be translated to "or null".

## To Reproduce

1. Given this OpenAPI document https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/digitalocean/openapi/main/specification/DigitalOcean-public.v2.yaml#/operations/create_volume_snapshot
2. Click create volume snapshot
3. See error

## Expected behavior

1. The Nullable badge should be removed.
2. `type: null` should show a type of `null` just like `type: string` shows `string`.
3. `type: ["string", "null"]` should show a type of `string or null`.
4. `type: string, nulllable: true` should show the same as 3.

**Screenshots**

type [string, null] works nicely

<img width="891" alt="image" src="https://user-images.githubusercontent.com/67381/113782933-ddc49280-972a-11eb-9311-bbdba44fad3b.png">

Nullable shows as a badge instead of "or null"

<img width="893" alt="Screen Shot 2021-04-06 at 9 19 31 PM" src="https://user-images.githubusercontent.com/67381/113774012-a3ed8f00-971e-11eb-93db-1fd369a24561.png">

type: null shows no type.

<img width="891" alt="Screen Shot 2021-04-06 at 9 19 48 PM" src="https://user-images.githubusercontent.com/67381/113774029-a94ad980-971e-11eb-81de-3a9be932e348.png">

**Comment by marcelltoth** [comment]
@P0lip Do you think this is something that will be made obsolete by your new `http-spec` feature? You know the one that transforms specs into the new format.

**Comment by P0lip** [comment]
@marcelltoth yeah, it should be addressed by that improved http-spec schema object converter.

**Comment by marcelltoth** [comment]
Great! What's the ETA on that? Is there an issue that we can track?

**Comment by P0lip** [comment]
https://github.com/stoplightio/platform-internal/issues/5879, ETA = today/tomorrow depending on how the review goes.

**Comment by philsturgeon** [comment]
***@***.*** was just released

Perhaps this issue is now about bumping to that and adding a test?

**Comment by marcelltoth** [comment]
FYI: That one is a new major, so we need to bump it everywhere.

**Comment by philsturgeon** [comment]
Ok, however you want to handle it. Close this and any other issues solved by the new major and make a single “bump and check these things issue” perhaps? 

--
Phil Sturgeon
Product @ Stoplight.io

**Comment by philsturgeon** [comment]
Superseded by #1116.
