### ISSUE TITLE
Remove examples from JSV

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1026]
## User story.

As a docs viewer, I can see the fully generated examples on the right column, so I no longer need to see singular examples in the middle column.

## Is your feature request related to a problem?

After reviewing elements with our awesome new response generator and some real world examples, it no longer feels like we need the "Example value(s)" listed in the middle col. There are some edge cases where there might be multiple example values and therefore some of them wouldn't be visible, but for the majority of cases this information is now redundant. 

## Describe the solution you'd like

Add an option that hides all examples in JSV, but keep allowed values and all other logic intact.

Do _not_ remove examples from headers/parameters/etc. Only JSV.

## Additional context

<img width="1065" alt="Screen Shot 2021-04-07 at 5 55 52 PM" src="https://user-images.githubusercontent.com/67381/113905004-98f03880-97ca-11eb-8e9d-044ee4da0151.png">

**Comment by marcelltoth** [comment]
Performance is a very good point, we'll see if it's adequate.

Simplicity wise, I'm totally with you @marbemac, I'd love to just add that prop and forget about the problem. But as we are building for the long-term, there are some maintainability and versioning questions. Don't forget that JSV is public, but even if it wasn't, little props like this quickly accumulate, and they cause a maintenance burden:

1. When you have 10+ of these, it starts to become simply incomprehensible both for contributors and for users. Just look at what happened with `ui-kit`'s `TableOfContents`. (And I've already cleaned up some props there.)
2. Once you add those, there's no way back without a new major version. Which is a pretty big deal, especially as JSV is public.

So usually our strategy is to avoid adding functions, especially for stuff that is achievable using the current feature-set. Of course if performance or other needs necessitate, we'll need to do it.

I'll promise you we'll have the feature that you need implemented, and I trust the team with picking the right approach, taking all arguments into account.
