### ISSUE TITLE
JSV: anyOf/oneOf selector flashes on click

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1051]
## Describe the bug

When clicking the select dropdown for a oneOf, the dropdown vanishes and is unusable. Holding down click will work.

## To Reproduce

1. GitHub Demo > Get Installation: https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.0/ghes-3.0.json#/operations/apps/get-installation
2. Try and select a dropdown next to account

## Expected behavior

Normal select box behavior.

## Additional context

**Screenshots**

https://user-images.githubusercontent.com/67381/114582351-689c1480-9c78-11eb-89c9-ca5f20e43d1a.mov

**Environment (remove any that are not applicable):**
 - Library version: commit fc7ec6a
 - OS: macOS
 - Browser: Firefox 87
 - Platform: Demo

**Comment by mmiask** [comment]
@marbemac this turned out the be a non-issue for a fresh install. After we did a lockfile update, the old version of Mosaic (`.36`) is no longer used. I'll pin Mosaic to the exact version in JSV though, to avoid potential crashes.

**Comment by marcelltoth** [comment]
> I'll pin Mosaic to the exact version in JSV though, to avoid potential crashes.

Why don't you let it float in JSV and pin in Elements? Or maybe it's like that already, then we can just close this. If it's pinned in Elements then (assuming the pinned version satisfies JSV's constraint) pinning it in JSV won't gain us anything, OTOH we are just making future mosaic updates more complicated for ourselves.
