### ISSUE TITLE
ToC: Use operationId before using path when summary is missing

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1056]
## User story.

As a user new to OpenAPI and Stoplight I might not have entered a summary for my operation, and I'd like my OpenAPI to still look as good as possible. In general I would like the ToC title to match the title displayed.

## Is your feature request related to a problem?

This is similar to #1035, in that the ToC and the Title of the page someone is looking at should agree with each other.

## Describe the solution you'd like

The ToC should use operationId before falling back to showing the path.

## Additional context

<img width="728" alt="Screen Shot 2021-04-14 at 11 27 07 AM" src="https://user-images.githubusercontent.com/67381/114696586-b9614b00-9d14-11eb-8a34-765db73c33f0.png">

<img width="795" alt="Screen Shot 2021-04-14 at 11 27 16 AM" src="https://user-images.githubusercontent.com/67381/114696588-b9f9e180-9d14-11eb-81ae-61905b453bbb.png">

You can use Stripe as an example: https://elements-demo.stoplight.io/?spec=https://api.apis.guru/v2/specs/stripe.com/2020-08-27/openapi.yaml#/operations/Post3dSecure

**Comment by DavidBiesack** [comment]
The "user" of the API doc is a developer. While some developers may call APIs via naked HTTP, many rely on code generation ( `openapi-generator` or other) to create an SDK, so the `operationId` becomes the name of a function. It is therefore connective glue in the API doc that connects the API operation to the SDK. It is also the name of the operation which developers use to communicate with other developers. It's a lot easier (more concise, more precise) to slack/email a reference to an operation via the `operationId` compared to using the method + path or the verbose summary. This, I think it is important enough to always show the `operationId` even if the operation has a summary.

**Comment by philsturgeon** [comment]
That sounds like another vote for "Custom SDK Samples" to me, as we'd not want end users needing to worry about operationId just so they can find the right SDK method to use. They'd just see the right method to use in the code sample panel.

**Comment by DavidBiesack** [comment]
I'm referring to a full API First OpenAPI pipeline where someone generates the SDK outside of the API doc snippets and uses the generated SDK in their client or server codebase. I'm not asking for custom SDK code samples. I don't think anyone copies/pastes code snippets from the API doc to build their SDK - that code is just for learning the API, or for toy applications, not using it in production.
Also, the default Spectral rules also want a unique `operationId` on each operation, so developers are already aware of it. Again, having an identifier to refer to the operation in other channels is very useful - "Look up the doc for createPerson ..."

**Comment by philsturgeon** [comment]
@DavidBiesack oh I definitely wasn't suggesting that. The use case you mentioned for operationId sounded like a crutch for proper SDK code samples, which can be achieve in various ways, discussing that over in #1137.

Again we separate internal users (who know about OpenAPI because they are writing it) and external users (who dont care at all about OpenAPI). We'd like to continue to only show external users things relevant to external users, and the operationId is in the URL if internal users would like to use that for communications about an operation. What better way to tell somebody the operation you're talking about than using its URL! :) 

Regardless, this issue is about using it as a fallback for ToC, so if #1137 isn't interesting to you please head over to the Discussions tab to chat about other ideas.
