### ISSUE TITLE
Lots of security badges stretch horizontally

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1063]
## Describe the bug

When there's a lot of security badges the screen runs off to the right instead of wrapping the badges.

## To Reproduce

1. Given this demo https://elements-demo.stoplight.io/?spec=https://api.apis.guru/v2/specs/googleapis.com/youtube/v3/openapi.yaml#/operations/youtube.channelBanners.insert
2. See error

## Expected behavior

Wrap the badges down to the next line with some reasonable top/bottom padding.

## Additional context

**Screenshots**

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/67381/114862997-188f9000-9de7-11eb-8bd9-4103190821e7.png">

_Lets not focus on the fact that they're all OAuth 2.0 for now, and come up with a feature to differentiate them later._

**Comment by mpodlasin** [comment]
Here is where the badges are displayed https://github.com/stoplightio/elements/blob/main/packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx#L55

**Comment by mpodlasin** [comment]
We got rid of security badges.
