### ISSUE TITLE
Hide body for 204

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1074]
Hide the Body dropdown and Mime Type Selector for 204 responses, because 204 means No Content. 

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/67381/114993063-5518c580-9e93-11eb-8cde-5cf2b495a333.png">

**Comment by mpodlasin** [comment]
To be hidden in this component https://github.com/stoplightio/elements/blob/main/packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx

**Comment by falsaffa** [comment]
Issue fixed a long time ago.
