### ISSUE TITLE
Hide API Base URL when there's garbage input

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1111]
## Describe the bug

The window with URLs is empty in some cases, especially when the URL specified is malformed. It shouldn't appear at all.

## To Reproduce

Visit https://api.apis.guru/v2/specs/britbox.co.uk/3.730.274-ref-1-39-0/openapi.yaml in elements demo.

## Expected behavior

No window when there are no contents.

**Screenshots**
![Screenshot from 2021-04-22 10-22-50](https://user-images.githubusercontent.com/7916523/115681371-c2759c00-a354-11eb-8a49-12952aa531c9.png)

![Screenshot from 2021-04-22 10-15-40](https://user-images.githubusercontent.com/7916523/115681388-c6a1b980-a354-11eb-8b15-792515fc5903.png)

**Comment by philsturgeon** [comment]
Brilliant. 

@mpodlasin the logic you've been creating for how to come up with a default server in Request Samples could be moved higher up to make a server URL, then that server URL is displayed here and passed around to everything else as if it was defined.

**Comment by marcelltoth** [comment]
The URL of that spec keeps changing. Go to https://apis.guru/simple-ui/ then search for "britbox" (or just take any spec and break the server URL).
