### ISSUE TITLE
Upgrade to http-spec@v4 for OAS3.1 Support

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1116]
Upgrading to http-spec v4 will take care of https://github.com/stoplightio/elements/issues/1017 and a whole lot of other rubbish that we won't need to think about.

It's a beta right now but that's ok. 

There will be a few breaking changes: 

- exclusiveMinimum and exclusiveMaximum are integers not boolean modifiers
- It returns JSONSchema7 not JSONSchema4
- It's ditched openapi-sampler for @stoplight/json-schema-sampler and we might want to do the same
- Delete the `Nullable` tag, it should be normalized as "string or null" now. See https://github.com/stoplightio/elements/issues/1017 for more context.

**Comment by P0lip** [comment]
@marcelltoth I think you won't need to do anything here - I'm taking care of it at the moment, because I need it for Studio.
There might be some changes you'll want to address separately, but hopefully minor.

**Comment by marcelltoth** [comment]
@P0lip AFAICT your PR targets `v6`, so while this became much simpler because of it, we still need to port it to v7. Keeping this open still.

**Comment by P0lip** [comment]
> @P0lip AFAICT your PR targets v6, so while this became much simpler because of it, we still need to port it to v7. Keeping this open still.

Yup, I know. I had started the work on v7 (https://github.com/stoplightio/elements/commit/6016ca80380322d0ae74d04e532b6808b26aff3f, just pushed the latest code I had) before Jakub J picked it up, but when I realized he's on it, I decided not to interfere.
You shouldn't need any futher changes in JSV, because I took care of it.

**Comment by marcelltoth** [comment]
>  I'd like to stress we need this to be implemented ASAP, so if you need a hand, LMK.

That shouldn't really be the case, see Slack message. That being said, @mallachari 's PR should be there soon
