### ISSUE TITLE
Internal Story book components exposed publically

### ISSUE THREAD

**Issue by savage-alex** [stoplightio/elements#1127]
Unsure if it is on purpose or not but public (people like me) can access the internal folder on the story book instance: 
https://stoplight-elements.netlify.app/?path=/story/internal-docs--docs-story
![image](https://user-images.githubusercontent.com/25430683/116040535-0e318980-a664-11eb-932c-8bf4b6c16e87.png)

**Comment by philsturgeon** [comment]
Yeah this is ok. There's all sorts of stuff in this package thats unsupported and people can muck about with it if they want, but it's prone to change and not recommended. We'll be hiding storybook a little more, mainly its useful for contributors, and the demo is where people want to go to see how things look.

**Comment by savage-alex** [comment]
Perfect. We use it internally only so wanted to flag encase it wasnt supposed to expose all. Nice work!
