### ISSUE TITLE
"Powered by Stoplight"

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1130]
## Summary

We were so busy working on features and stability we forgot to sign our work! 

Here's how it should look:

![endpoint](https://user-images.githubusercontent.com/67381/116061398-b4888980-a67a-11eb-81cd-40682e520d6f.png)

We already have similar in hosted docs, but we're going with purple here. 

Link should be:

```
https://stoplight.io/?utm_source=elements&utm_medium=api&utm_campaign=powered_by&utm_content=/
```

**Comment by philsturgeon** [comment]
@smf434 @mnaumanali94 how does that look for the UTM link? ☝🏻

**Comment by mnaumanali94** [comment]
Could the medium potentially be the API name here? It would be interesting to see where it's coming from

**Comment by philsturgeon** [comment]
@mnaumanali94 by api name do we mean info.title? We can do that. It’ll have a bunch of duplicates like User API, but it can give us some idea of what APIs are doing well I suppose? Anything more specific would be invasive.

**Comment by mnaumanali94** [comment]
That aligns with what I was thinking. 💯
