### ISSUE TITLE
[Spike] Come up with main areas of Elements that need additional testing

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/elements#1141]
## Summary

As we discussed last time, there is a need for an additional layer of testing beyond our unit tests, mostly towards the UI piece, to give us confidence that the major functions are intact. This will likely take form of 2-3 real E2E flow tests, and/or optionally some Jest based integration testing. 

## Tasks

The output of this spike is a list. Go through elements, and come up with a list of major areas you would like the E2E flow to touch. Consider what can and what cannot be efficiently tested using unit tests, and try to focus on the ones that cannot.

**Comment by mpodlasin** [comment]
Some ideas after recent bugs we encountered:

- each page *type* - article, service, operation, model, etc. - should have a test if this page *type* is correctly displayed.
- check (custom) icons (???)
- send a request with TryIt
- check generated RequestSample content

**Comment by marcelltoth** [comment]
Closing this as @mpodlasin already completed the spike with the list above.
