### ISSUE TITLE
Remove generateAPIToc from elements-utils

### ISSUE THREAD

**Issue by lottamus** [stoplightio/elements#1142]
Since `elements-utils` is not used for API toc generation anymore, we should remove API-related functionality from that package. We can make this in a separate issue, so after this gets merged, let's create an issue covering that.

_Originally posted by @mpodlasin in https://github.com/stoplightio/elements/pull/1110#discussion_r621125544_

**Comment by philsturgeon** [comment]
Let's handle as part of #959.

**Comment by marcelltoth** [comment]
We can also rename this to *Remove `elements-utils`*, can't we? cc @mpodlasin
