### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1149]
## User story.

As a fan of dark mode, I want dark mode everywhere, so I can always view everything in dark mode.

## Is your feature request related to a problem?

Not enough dark mode! 

## Describe the solution you'd like

Needs more dark mode. 

## Additional context

Blocked by #957.

**Comment by jasonm23** [comment]
tl;dgdrh ... (too long, didn't go down rabbit hole)

```html
<html lang="en" data-theme="dark">
```

NOTE: the syntax highlighting for responses and code samples are not changed for dark mode, and need attention
