### ISSUE TITLE
Make schema view "flatten" allOf consistently

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1158]
## Describe the bug

We might not be using allOf consistently when rendering schemas in request/response vs schema view.

## To Reproduce

When looking at the requestBody schema from the [List sub accounts](https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/stoplightio/Public-APIs/master/reference/zoom/zoom.yaml#/operations/accounts) endpoint of the Zoom API the schema is "merged" into a single object.

![image](https://user-images.githubusercontent.com/67381/116869959-f6cd4000-ac11-11eb-92b5-76e900f72ff4.png)

However, when looking at the [same schema directly](https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/stoplightio/Public-APIs/master/reference/zoom/zoom.yaml#/schemas/AccountList) the schemas are not merged. You can see it's composed of multiple schemas. 

![image](https://user-images.githubusercontent.com/67381/116869966-f9c83080-ac11-11eb-88cf-11cdc26eab85.png)

## Expected behavior

The two renderings of the same schema should look the same, but we might be handling allOf differently in these two different locations.

**Comment by raleigh04** [comment]
Phil says this should be fixed for GA (end of May).

Is this JST or something else?

@P0lip thoughts?

**Comment by P0lip** [comment]
It's not JST. It's an issue with elements.
This is the culprit
See https://github.com/stoplightio/elements/blob/main/packages/elements/src/components/SchemaAndDescription.tsx#L45L46

![image](https://user-images.githubusercontent.com/9273484/117064148-18b7e700-ad26-11eb-940c-6775c7dadcc0.png)
![image](https://user-images.githubusercontent.com/9273484/117064201-2e2d1100-ad26-11eb-84bd-9f27f5fd2c5e.png)
