### ISSUE TITLE
Schemas are not displayed in CRA example

### ISSUE THREAD

**Issue by mmiask** [stoplightio/elements#1163]
## To Reproduce

1. Checkout `main` - `356fff0e66c9909dcbb98b91eefb970ac7f648bb`
2. run `yarn && yarn build && yarn build:react-cra && yarn serve:react-cra`
3. Open the example
4. Open any endpoint/schema

## Expected behavior

Users should see schemas displayed

**Screenshots**

<img width="795" alt="Screenshot 2021-05-04 at 15 49 17" src="https://user-images.githubusercontent.com/58433203/117014535-2d2dbc80-acf1-11eb-9fda-de3b308b29b3.png">

**Environment (remove any that are not applicable):**
 - OS: MacOS 11.3.1 (20E241)
 - Browser: Chrome 90

**Comment by philsturgeon** [comment]
It's not just on the Schema View page and its not just CRA, this is the react gatsby example:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/67381/118022732-95fde000-b354-11eb-9460-b3728aacd94c.png">
