### ISSUE TITLE
[StoplightProject] redirect doesn't work in CRA install

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1212]
After installing `elements-dev-portal` to a new CRA project (**not** using examples one), and using `StoplightProject` component, the component doesn't redirect user to a proper entry in ToC, leaving the page blank.

Clicking on ToC entries works correctly.

![Screenshot from 2021-05-11 11-43-11.png](https://images.zenhubusercontent.com/5f857aaa311cec7e20b4f258/3b739551-def1-4937-9120-d7eb3ce79374)

**Comment by lottamus** [comment]
I'm fairly confident this will be fixed with https://github.com/stoplightio/elements/pull/1195

**Comment by mpodlasin** [comment]
Perhaps. But it works in *most* of the places, like storybook and our own examples, which makes me question if there is some compatibility issue with newer CRA versions.

We plan to update our examples soon anyways, so perhaps this will allow to test your new version @lottamus
