### ISSUE TITLE
Remove storybook/babel warning

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1214]
![Screenshot from 2021-05-11 12-47-33](https://user-images.githubusercontent.com/7916523/117803651-2c4bdc00-b257-11eb-8eea-66688d4338f4.png)

**Comment by mallachari** [comment]
Looks like this is not the case anymore. Or at least I can't reproduce it.

**Comment by mnaumanali94** [comment]
Can we close this @mallachari @mpodlasin then?

**Comment by mpodlasin** [comment]
Yup, it's gone.
