### ISSUE TITLE
Make `examples` more independent.

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1267]
Currently examples - `angular`, `react-gatsby` and `react-cra` - require user to make a build of `elements` and `elements-dev-portal` before running them.

On top of that they have `package.json` differences from a regular project, that make them impossible to copy&paste somewhere and run indepedently without refactoring `package.json` first.

We want to change that.

**AC:**
- examples use actually released packages by default (for example `elements@7.0.0.-beta.X` etc.)
- you can clone repo, immediately go to an example folder and run it using only standard commands of that repo (`yarn` & `yarn start`).
- you can copy&paste example folder to another directory and run it in the same way as above
- *and yet* the e2e tests still work and they use *builds from a repo, not released packages*

So far we have 2 potential ways to achieve this:
- use `yarn link` before running e2e tests to direct examples to `dist` folders generated in the repository
- copy & paste example folders to some temporary location, rewrite (using a script) package.json to use the file paths we currently have in them, then run the tests

If however you have any other ideas how to implement this feature, they will be appreciated.

Bonus points:
- being able to run examples using repo builds *outside of e2e tests* in a fairly easy way
- not having to use `yarn reinstall` after every new build of `elements` or `elements-dev-portal` to see changes

**Comment by philsturgeon** [comment]
When working on this please update the following docs with any changes to how things work.

- docs/getting-started/2-integrations/angular.md
- docs/getting-started/2-integrations/gatsby.md
- docs/getting-started/2-integrations/next.md
- docs/getting-started/2-integrations/react.md
