### ISSUE TITLE
New Gatsby Starter 

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1270]
Let's bring back the elements-starter-gatsby repository, redone for elements v7. 

**Acceptance Criteria**

- Update https://github.com/stoplightio/elements-starter-gatsby repo for elements v7
- Update docs: docs/getting-started/2-integrations/gatsby.md

**Comment by philsturgeon** [comment]
cc @audieleon

**Comment by mpodlasin** [comment]
Repo for elements is here: https://github.com/stoplightio/gatsby-starter-elements

**Comment by mpodlasin** [comment]
Repo for elements dev portal is here: https://github.com/stoplightio/gatsby-starter-elements-dev-portal
