### ISSUE TITLE
New React Starter

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1271]
Let's bring back the elements-starter-react for elements v7 so people can get up and running with React in a single command. 

Instead of adding yet another example, create a [custom template](https://create-react-app.dev/docs/custom-templates/) and update docs to talk about how to use them.

**Comment by mpodlasin** [comment]
Elements car template: https://github.com/stoplightio/cra-template-elements

**Comment by mpodlasin** [comment]
Elements Dev Portal cra template: https://github.com/stoplightio/cra-template-elements-dev-portal
