### ISSUE TITLE
Base URL in Request Samples is not correct.

### ISSUE THREAD

**Issue by K2ouMais** [stoplightio/elements#1296]
Hello everyone,

when I set my base URL like ```http://example.com/api``` it seems that the base URL is not correct on all request samples.

It seems that the ```/api``` is missing everywhere.

![Base_URL](https://user-images.githubusercontent.com/52510455/118829547-7e77a780-b8be-11eb-8925-2821a7caf296.png)
![Request_Sample](https://user-images.githubusercontent.com/52510455/118829563-80da0180-b8be-11eb-973c-dd4fd0a1751b.png)

**Comment by mpodlasin** [comment]
Hey, have you checked elements 7.0.0-beta.3? This issue should be already resolved.

**Comment by mpodlasin** [comment]
Aah, sorry. Just had a peek at the codebase and can confirm that this is indeed an issue.

We will fix it ASAP, thank you for reporting!

**Comment by K2ouMais** [comment]
Is there a new beta that I can try?

Thank you

**Comment by marcelltoth** [comment]
Hey @K2ouMais! I'm happy to let you know we just released `7.0.0-beta.4` which contains the fix to your problems! 🚀 Let me know if there's anything else that pops up.

**Comment by K2ouMais** [comment]
Thank you... Everything is now working like it should.
