### ISSUE TITLE
Add internal badge to elements

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#1325]
If an endpoint/model contains x-internal:true, add an internal badge on it. 

![Screenshot 2021-05-24 at 10.12.50 PM.png](https://images.zenhubusercontent.com/5ea9a7f489044245dbd23d46/56178281-a887-4779-9338-ba0ca6e2e10c)

**Comment by paulatulis** [comment]
@mnaumanali94 should the internal badge include a tooltip?

**Comment by mnaumanali94** [comment]
This endpoint/model is marked as internal and won't be visible in public docs.
