### ISSUE TITLE
No readOnly properties in "Response Example"

### ISSUE THREAD

**Issue by ugnich** [stoplightio/elements#1369]
## Describe the bug

When the property is readOnly it's not showing in "Response Example". If I change it to "Read/Write" - will show.

## To Reproduce

1. Use https://unpkg.com/@stoplight/elements@beta/web-components.min.js 
2. Use yaml file below.

## Expected behavior

Read-only properties should be shown in response examples.

## test.yaml

```
openapi: 3.1.0
paths:
  /websites:
    get:
      responses:
        '200':
          $ref: '#/components/responses/WebsitesNames'
      operationId: get-websites
components:
  responses:
    WebsitesNames:
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 1
                  example: 1
                  readOnly: true
                name:
                  type: string
                  example: My Website
                  minLength: 1
              required:
                - id
                - name
```

## Screenshot

![Screenshot from 2021-06-03 17-32-32](https://user-images.githubusercontent.com/1279481/120624486-54fc7580-c493-11eb-9445-776c2c6f0e62.png)

**Comment by marcelltoth** [comment]
Hi @ugnich , thanks for reporting this.

It seems like a valid bug we will have to work on. We'll prioritize it and get back to you. If you are maybe willing to send us a PR, that would of course help, let us know.:)
