### ISSUE TITLE
Collapse Top Level ToC

### ISSUE THREAD

**Issue by marbemac** [stoplightio/elements#1370]
ToC is currently automatically expanding everything, which in projects with a lot of content takes up a huge amount of space, as APIs with lots of operations, or articles with lots of sub folders, can be nested to pretty much infinite levels. 

<p></p>

Different people have different preferences over whether they should be expanded to save clicks, or collapsed to save space/scrolling.

<p></p>

Add a new option for StoplightProject of `collapseToc: true` which will collapse everything in a group to the highest level.

![](https://pb-files.s3.amazonaws.com/production/attachments/f8db62194ddbc54ba311b5afd3fae0077c70d2c90022ae813ed7a4ed3cbc9902/image.png)

- API's will be closed so tags and untagged operations will not show up until expanded.

- Nested folders will be collapsed, so no nested articles will show up.

- Update documentation for Elements (Web and React), and Dev Portal (Web and React).

<p></p>

The project used for this example is <https://philsturgeon.stoplight.io/docs/dev-portal-demo/> which has a projectId of "cHJqOjY1MzEw".

**Comment by marbemac** [comment]
Link to feature: https://stoplightio.productboard.com/feature-board/planning/features/6575160

**Comment by philsturgeon** [comment]
@audieleon

**Comment by marcelltoth** [comment]
@philsturgeon Do we need this on the API component, too?

**Comment by philsturgeon** [comment]
No I think just stoplightproject as it’s having many APIs and deeply nested articles that’s the problem.
