### ISSUE TITLE
Support each type of example for parameters

### ISSUE THREAD

**Issue by mmiask** [stoplightio/elements#1399]
## Describe the bug

This is a follow-up to https://github.com/stoplightio/platform-internal/issues/5372 - Elements v7 don't crash but aren't displaying validations correctly either.

https://user-images.githubusercontent.com/58433203/121709937-5bb16b00-cad9-11eb-81dc-acbf9bd05adb.mp4

## To Reproduce

Follow the steps from the related issue:
1. Download provided files
2. Create a project in a workspace with those files
3. Run this project in StoplightProject
4. Go to any endpoint under `Content Request Service`

## Expected behavior

Instead of:
![Screenshot 2021-06-11 at 17 14 43](https://user-images.githubusercontent.com/58433203/121709136-864ef400-cad8-11eb-818e-5d414da141df.png)

the desired `examples value should be:
![Screenshot 2021-06-11 at 17 16 13](https://user-images.githubusercontent.com/58433203/121709340-bd250a00-cad8-11eb-890e-6c72be006698.png)

## Additional context
Docs part is already fixed in `v6`

**Environment (remove any that are not applicable):**
 - Library version: `main` - `7798fe58e7b02837b084ac477ea9343a13912881`
 - OS: MacOS 11.4 (20F71)
 - Browser: Chrome 91

**Comment by philsturgeon** [comment]
What OpenAPI is creating this? Do you have a file I can look at?

**Comment by mmiask** [comment]
> What OpenAPI is creating this? Do you have a file I can look at?

@philsturgeon I used the file provided by Erik in the connected issue. Make sure to import the whole directory though, as the API document uses some standalone models
