### ISSUE TITLE
Schema rendering error for arrays of arrays

### ISSUE THREAD

**Issue by mikirockerful** [stoplightio/elements#1418]
## Describe the bug

In the Stoplight web editor, a model definition including an array of arrays results in the schema not being rendered with the error: `Error: cannot use 'in' operator to search for "writeOnly" in "array"`

Check screenshot below.

## To Reproduce
1. Given this OpenAPI document:
```yaml
openapi: 3.0.0
info:
  title: Issue demo
  version: 1.0.0
  description: Demo
paths:
  /test:
   get:
    responses:
     '200':
        description: List of all booking questions for this session
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyNestedArray'
components:
  schemas:
    MyNestedArray:
      type: object
      properties:
        my_nested_array:
          type: array
          items:
            type: array
            items:
              type: string
```
2. Import it into an new project in Stoplight. The preview of the `MyNestedArray` schema will display the following error, instead of displaying the schema:
```
Error: cannot use 'in' operator to search for "writeOnly" in "array"
```
## Expected behavior

Since the OpenAPI specification is valid, I'd expect the schema to be rendered, displaying the property as an array of arrays. In other editors I've tried, the schema is being displayed correctly.

## Additional context

**Screenshots**
![image](https://user-images.githubusercontent.com/18682844/121885283-45dbba00-cd14-11eb-96b0-6838abc2b741.png)

**Environment (remove any that are not applicable):**
 - Library version: OpenAPI 3.0.0
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Firefox 89.0
 - Platform:  web

**Comment by philsturgeon** [comment]
Discovered in v6, but we should make sure its all good in v7.

**Comment by mallachari** [comment]
It is all good in v7. As we will replace v6 soon it doesn't make sense to fix it there. 
@philsturgeon should we close it now or wait for v7 to be officially in platform?

**Comment by philsturgeon** [comment]
Good to know! I’ll reach out to the OP and see if they want to enable new docs on their workspace.
