### ISSUE TITLE
Mocking (sometimes) doesn't work (?)

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1435]
## Describe the bug

From time to time mocking doesn't seem to work for me.

I am either getting CORS error or some other message:

<img width="1409" alt="Zrzut ekranu 2021-06-16 o 13 23 07" src="https://user-images.githubusercontent.com/7916523/122219259-8cb1e700-ceaf-11eb-84ac-8fa699a375c3.png">

## To Reproduce

1. Run react-cra example.
2. Make few mocked requests on different APIs and different operations

## Expected behavior

CORS enabled for any host.

**Comment by rainum** [comment]
after chatting with @mpodlasin we figured out that this is not happening anymore. Closing

**Comment by mpodlasin** [comment]
I am reopening. Same issue as before.

I am dropping full response, in case it "disappears" again:

```json
{
  "name": "https://stoplight.io/prism/errors#NO_PATH_MATCHED_ERROR",
  "status": 404,
  "detail": "The route /v1/paymenttransaction/%7BoriginatorId%7D/%7BdestinationId%7D/%7BtransactionId%7D/v1/paymenttransaction/originatorId/destinationId/transactionId hasn't been found in the specification file",
  "additional": {
    "workspaceSlug": "mp-test",
    "projectSlug": "cool",
    "url": "/v1/paymenttransaction/%7BoriginatorId%7D/%7BdestinationId%7D/%7BtransactionId%7D/v1/paymenttransaction/originatorId/destinationId/transactionId",
    "code": 200,
    "dynamic": false
  }
}
```

<img width="530" alt="Screenshot 2021-07-05 at 18 29 42" src="https://user-images.githubusercontent.com/7916523/124500436-145c8880-ddc0-11eb-9435-67cc5d9db25d.png">

Docs: https://mp-test.stoplight.io/docs/cool/b3A6NzM1MTg5MQ-abfrage-einer-payment-transaction-insb-um-den-status-zu-pruefen

**Comment by chohmann** [comment]
@mpodlasin at first glance this doesn't really look like the same original issue. Originally it looked like you were getting CORS issues? Now the request path isn't matching one in the spec? Is that correct?

Also, do you have the spec you're trying to mock?

@rainum is planning on looking into this with you during y'alls day tomorrow.

**Comment by chohmann** [comment]
@mpodlasin it looks like you're including the `{` in your request to the mock server based on the `%7B` showing up in the url of the request:

`/v1/paymenttransaction/%7BoriginatorId%7D/%7BdestinationId%7D/%7BtransactionId%7D/v1/paymenttransaction/originatorId/destinationId/transactionId`

Can you check to make sure the url in your request to the mock server is correct?

**Comment by mpodlasin** [comment]
@chohmann aaaah, I see - it's possible, we had problems with those before. 🤦 

I guess I was just confused by the messaging from the API. But you are 100% correct, we were sending malformed requests.

Let's leave this issue to us then, we have to improve error handling and error messaging so that users know exactly what is going on.
