### ISSUE TITLE
Fix hide "Powered by Stoplight" for Professional Plan

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1438]
## User story.

As a StoplightProject user on a Professional plan, I can hide Powered by Stoplight, so that I can keep people looking at my docs instead of being distracted by Stoplight's awesome tooling.

## Is your feature request related to a problem?

Hosted Docs will let Workspace Admins hide "Powered by Stoplight" as part of the Professional plan, but currently StoplightProject shows it for all projects all the time. 

## Describe the solution you'd like

Check the plan or check settings to see if they would like to hide "Powered by Stoplight"

**Comment by marcelltoth** [comment]
API and frontend logic is there, the problem is that the api returns `hidePoweredBy` while we expect `hide_powered_by`
