### ISSUE TITLE
[spike] Support internal and private projects in Stoplight Project

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1440]
Currently StoplightProject only supports public projects. We need to find a way to get StoplightProject to work with internal and private projects too.

Currently there is an auth token for publishing projects via the CLI. Using the same token and making at a property (e.g.: `<StoplightProject authToken="foo"`) would probably be a security issue, because anyone who can see the web component HTML would then be able to publish. 

We could make another auth token that is passed along with the node/branches/toc requests, that will allow the project to be displayed instead of the current 404?

If so, where do they find that auth token? Maybe project settings could have an "Embed" or "Widget" tab on the settings, and they can find complete HTML/JS code to embed Elements anywhere, like getting HTML from YouTube to embed a video?

Outcome of spike:

1. Define how the auth token or "elements secret" will work.
2. Figure out where the token/embed will be in product.

**Comment by philsturgeon** [comment]
@lottamus if you have any feedback on this topic we might be able to upgrade this from a spike to a story.

**Comment by marbemac** [comment]
This will take a pretty decent chunk of work. At a high level the only way I can think to do this without security issues is to allow end users to login/signup (to stoplight, via whatever integrations are setup on the workspace), and then pass their token along with the API requests. Were we to go down this route I think we need to step back and figure out how this would fit into the whole account types, guests, and pending requests systems. Given the amount of work represented with the above, unsure if it's worth trying to tackle here in the short term?

Open to other ideas of course.

**Comment by philsturgeon** [comment]
The most common feedback we've had so far from people trying to use StoplightProject is "It seems to only works with public projects, and we need it to work with a private project".

I don't think we need to get as extreme as that with forcing logins, at least not right away. People are going to be placing this HTML into their existing dev portals, CMS, VPN, etc., so nobody should see that authToken who isn't meant to. If they do see it, then can see docs, and that seems like a decent tradeoff? I suppose if there's just the one token then it wouldn't help us with the internal vs private differentiation, but it would get us out of "public only", and we already have a hideInternal option planned.

**Comment by philsturgeon** [comment]
Closing in favour of #1463 for now. We'll allow people to log in, and if they log in they can see internal/private projects.
