### ISSUE TITLE
[demo] unreadable button on navigation

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1441]
## Describe the bug

Button on the right, leading to stoplight website is unreadable:

<img width="1421" alt="Zrzut ekranu 2021-06-17 o 11 47 52" src="https://user-images.githubusercontent.com/7916523/122374989-1e2e6100-cf63-11eb-8bf4-3f2f5a84aa42.png">

## To Reproduce

Visit https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.0/ghes-3.0.json#/operations/search/code

## Expected behavior

a) looks cool
b) is readable

**Comment by mpodlasin** [comment]
New insight - appears only on safari.

@philsturgeon does this change priority?

**Comment by philsturgeon** [comment]
Yeah, bumped this to longterm.

**Comment by marcelltoth** [comment]
Not reproducible anymore.
