### ISSUE TITLE
npm install of elements fails when using react 17 and npm 7

### ISSUE THREAD

**Issue by damianpm** [stoplightio/elements#1447]
## Describe the bug

Installation of React component, `@stoplight/elements@beta`, fails due to conflicts with dependency resolution

## To Reproduce

1. Install dependencies:
```
npm install @stoplight/elements@beta
```

2. See error:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @stoplight/ui-kit@3.0.0-beta.39
npm WARN node_modules/@stoplight/ui-kit
npm WARN   @stoplight/ui-kit@"^3.0.0-beta.39" from @stoplight/elements@7.0.0-beta.5
npm WARN   node_modules/@stoplight/elements
npm WARN     @stoplight/elements@"7.0.0-beta.5" from the root project
npm WARN   1 more (@stoplight/elements-core)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @stoplight/ui-kit@">=2" from @stoplight/markdown-viewer@4.3.4
npm WARN node_modules/@stoplight/markdown-viewer
npm WARN   @stoplight/markdown-viewer@"^4.3.3" from @stoplight/elements-core@7.0.0-beta.8
npm WARN   node_modules/@stoplight/elements-core
npm WARN   1 more (@stoplight/json-schema-viewer)
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @stoplight/ui-kit@3.0.0-beta.39
npm WARN node_modules/@stoplight/ui-kit
npm WARN   @stoplight/ui-kit@"^3.0.0-beta.39" from @stoplight/elements@7.0.0-beta.5
npm WARN   node_modules/@stoplight/elements
npm WARN     @stoplight/elements@"7.0.0-beta.5" from the root project
npm WARN   1 more (@stoplight/elements-core)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @stoplight/ui-kit@"^3" from @stoplight/json-schema-viewer@4.0.0-beta.19
npm WARN node_modules/@stoplight/json-schema-viewer
npm WARN   @stoplight/json-schema-viewer@"4.0.0-beta.19" from @stoplight/elements-core@7.0.0-beta.8
npm WARN   node_modules/@stoplight/elements-core
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.4 || ^17.0.0" from @redocly/react-dropdown-aria@2.0.12
npm ERR!   node_modules/@redocly/react-dropdown-aria
npm ERR!     @redocly/react-dropdown-aria@"^2.0.11" from redoc@2.0.0-rc.54
npm ERR!     node_modules/redoc
npm ERR!       redoc@"^2.0.0-rc.54" from the root project
npm ERR!   peer react@"^16.8.0 || ^17" from mobx-react@7.2.0
npm ERR!   node_modules/mobx-react
npm ERR!     mobx-react@"^7.2.0" from redoc@2.0.0-rc.54
npm ERR!     node_modules/redoc
npm ERR!       redoc@"^2.0.0-rc.54" from the root project
npm ERR!   21 more (mobx-react-lite, react-copy-to-clipboard, react-dom, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-simple-code-editor@0.11.0
npm ERR! node_modules/@stoplight/mosaic-code-editor/node_modules/react-simple-code-editor
npm ERR!   react-simple-code-editor@"^0.11.0" from @stoplight/mosaic-code-editor@1.0.0-beta.58
npm ERR!   node_modules/@stoplight/mosaic-code-editor
npm ERR!     @stoplight/mosaic-code-editor@"1.0.0-beta.58" from @stoplight/elements-core@7.0.0-beta.8
npm ERR!     node_modules/@stoplight/elements-core
npm ERR!       @stoplight/elements-core@"7.0.0-beta.8" from @stoplight/elements@7.0.0-beta.5
npm ERR!       node_modules/@stoplight/elements
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/damian/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/damian/.npm/_logs/2021-06-17T13_08_56_388Z-debug.log
```

## Expected behavior

@stoplight/elements@beta is correctly installed

## Additional context

Node: v14.17.1
Npm: 7.17.0

Other dependencies (React):

```
"react": "^17.0.0",
 "react-dom": "^17.0.0",
```

**Environment (remove any that are not applicable):**
 - OS: Mac OS Big Sur

**Comment by mpodlasin** [comment]
I could indeed replicate. Thanks for reporting @damianpm.

<img width="400" alt="Zrzut ekranu 2021-06-25 o 10 07 26" src="https://user-images.githubusercontent.com/7916523/123392373-43dbeb80-d59d-11eb-9dbe-ab0ab6a3637a.png">

We are currently mostly using npm 6 and/or yarn, that's why we didn't see the error. If you want to try out elements, using npm 6 or yarn would be a temporary workaround.

**Comment by marcelltoth** [comment]
@damianpm thanks for reporting this. 

Unfortunately this is a [problem of our dependency](https://github.com/satya164/react-simple-code-editor/issues/75). It already has [a PR](https://github.com/satya164/react-simple-code-editor/pull/84) but the owner of the package doesn't seem to be around anymore. We are hoping the situation will get resolved soon, in the meanwhile the workaround is to use NPM v6 or Yarn.

@marbemac can we come up with a backup plan in case RSCE turns out to be totally abandoned? Maybe swap it for something, fork it, or inline it into mosaic?

**Comment by marbemac** [comment]
@marcelltoth for sure - any preference between fork it or inline into mosaic (I'd prefer not to switch libraries atm)?

**Comment by marcelltoth** [comment]
@marbemac I think you have infinitely more context on this than I do. My observations:
- It's a single ~600 LOC file so shouldn't be that hard to inline
- It's written with flow, although it isn't too far from TypeScript so for 600 lines it'd be fine.
- If seems abandoned though so with a well maintained fork we can probably quickly gain some traction, should we decide to maintain it long term

So I'd say in case we'd like to go with that package long term, potentially improving it and building some community support for it we could fork it. If we'd like to treat it as an implementation detail that works for now but we might switch it any time we encounter a better one (even if not right now) I'd inline it rather. One less dep in the tree anyway.

**Comment by damianpm** [comment]
I can confirm using **yarn** works as a workaround!
We are going to test it using yarn, but it would be great to be able to use npm 7 too.

**Comment by marcelltoth** [comment]
Hey @damianpm!

I'm happy to let you know that the stable version of `@stoplight/elements` fixes the problem. Just ran a test with latest Node (16.4.2) and latest NPM (7.19.1) and it ran perfectly smoothly.:)

<img width="409" alt="image" src="https://user-images.githubusercontent.com/543372/125065176-cbebe600-e0b1-11eb-8656-88ff18e40f1f.png">

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/543372/125065437-18cfbc80-e0b2-11eb-8265-5bfb6e9eca24.png">

(This is a fresh CRA with React `17.0.2`)

Let me know if you still see any problem even with the stable release, we'd love to assist.

**Comment by damianpm** [comment]
Thanks!
