### ISSUE TITLE
Hide Internal Operations / Models [StoplightProject Component]

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1472]
## User story

As a Stoplight Studio user, I can mark operations and models as internal, so that they will be hidden from external users.

## Is your feature request related to a problem?

Studio recently added an Internal toggle, which adds `x-internal: true` to operations and models that should be hidden from logged out users in our hosted docs solution. <https://github.com/stoplightio/platform-internal/pull/6340/>

We should replicate this functionality in elements v7, so that our hosted docs users continue to have this feature.

## Describe the solution you'd like

- In Platform, the TOC still shows internal endpoints/models. Lets hide them.

- For StoplightProject: Filter/hide results that have internal: true in the node data property. Look to see if internal: true/false is in node data from API, if not we'll to add it.

**Comment by mmiask** [comment]
Re-opening due to https://github.com/stoplightio/platform-internal/pull/7948

**Comment by mmiask** [comment]
For this issue make sure we address the following:

1. `branchSlug` support in `useGetNodes` - as of right now changes made in https://github.com/stoplightio/platform-internal/pull/7844 don't support searching within specific branch
2. You can find internal endpoints in search results (they are found in the API document and returned in search). They are not visible as standalone entities but their names are highlighted in API documents
<img alt="Screenshot 2021-09-06 at 11 53 22" width="718" src="https://user-images.githubusercontent.com/7916523/132198650-5f87a60c-677d-4db4-850a-b40d58f40c13.png">
