### ISSUE TITLE
StoplightProject: Jumpy Send Request button

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1496]
## Describe the bug

The "Send Request" button in Try It is changing width on click due to the font weight changing to bold, and this is pushing the mocking button. This makes the page look a bit "jumpy".

## To Reproduce

1. Load up any StoplightProject instance, in storybook, or examples.
2. Click Send Request
3. See error

## Expected behavior

I dont think we need to make this bold, so if we remove that it should just stay the same width when active.

**Screenshots**

https://user-images.githubusercontent.com/67381/123607681-032adf00-d7f6-11eb-99fa-656c6bf3b5f5.mov

**Environment (remove any that are not applicable):**
 - Library version: main @ c881c06
 - OS: macOS 11.4
 - Browser: 89.0.2 (64-bit)

**Comment by mpodlasin** [comment]
The problem is actually with a loading icon that mosaic `Button` has built-in.

It works in demo, but doesn't in storybook or examples - I have no clue why.
