### ISSUE TITLE
Unable to generate sample code due to util.format undefined

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1518]
Customer reported sample code still not working. "Unable to generate sample code" is showing, and this is the error in the console. 

![image.png](https://images.zenhubusercontent.com/5d1f7c5b8a1fa426d066830f/77d1e5d8-0f73-4175-8033-9f9f83df3674)

**Comment by mpodlasin** [comment]
`yarn add util` or `npm install util` in the repo where the problem appears will help.

It's a dependency required by httpsnippet library.

**Comment by philsturgeon** [comment]
@audieleon here is a workaround for the Unable to generate request sample error you're seeing. ☝🏻 

We'll leave this issue open until we find a way to solve this in all node environments, because it works in some and not in others.

**Comment by mpodlasin** [comment]
It would be good to just add httpsnippet "node" dependencies to dependencies of elements-core: `util` and `process`. This would ensure that stuff works in most environments, I believe.

`process` is already added as dependency for Gatsby. After it's added to elements-core, it should be removed from there.

**Comment by mpodlasin** [comment]
Additional context: the reason this error was so elusive to us is that webpack 4 adds those node dependencies by itself.

We use storybook and create-react-app a lot and both of them use webpack 4.

In fact, I believe we almost by accident use webpack 4 to build web components as well, which likely would be good to change. I'll create an issue for that.

**Comment by audieleon** [comment]
> `yarn add util` or `npm install util` in the repo where the problem appears will help.

Wanted to confirm for you that this worked on my project. (And I've incorporated the changes that removed webpack). 

Thank you.
