### ISSUE TITLE
Bootstrap website is not working on mobile device

### ISSUE THREAD

**Issue by saargospa** [stoplightio/elements#1527]
When I click hide the sidebar, it doesn't. Then users can't navigate via their phones.

## To Reproduce
Using bootstrap elements project version 6

**Screenshots**
![image](https://user-images.githubusercontent.com/43756439/124116491-fd730a80-da3c-11eb-9763-22c8ba11471c.png)

 - Browser: [Chrome]
 - Platform: [web]
 - Simulation [Iphone X]

**Comment by philsturgeon** [comment]
Elements v7.0 does not have a mobile layout yet, so none of the examples will either. The stacked layout will be the basis of the mobile view in the future, but for now that has to be enabled. 

It's something we've got on the roadmap but not sure when it will be done.
