### ISSUE TITLE
Cookies are not included in the request

### ISSUE THREAD

**Issue by haseebeqx** [stoplightio/elements#1548]
I wanted to try an api that involves cookies. Currently no cookies were sent while trying the api. 

Is there an option to disable this default behaviour and send cookies like a regular web request.

## Expected behavior

There should be an option to sent cookies if required.

**Comment by philsturgeon** [comment]
This is sadly not possible due to the way browsers handle cookies. You can disable Try It with hideTryIt+true if its not useful for your API.

**Comment by haseebeqx** [comment]
@philsturgeon I was able to fix  this by changing https://github.com/stoplightio/elements/blob/42b2118aa4ef286b3fdaf0858ac425475008d1ff/packages/elements-core/src/components/TryIt/build-request.ts#L73
 to
```js
credentials: 'same-origin' 
```

If you want I can contribute to this repo by adding an addidional option field `TryItCredentialPolicy` with default value of `omit` and user can set `include` or `same-origin` .

Reopen this issue if you are interested.

**Comment by philsturgeon** [comment]
Very interested! See if you can pull request something and I'll take a look.

**Comment by mnaumanali94** [comment]
Need to review and merge this pull request.

**Comment by wmhilton** [comment]
@mallachari @mmiask @mpodlasin @paulatulis Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/-Team-Pierogi-Platoon-610871b8d6e5310013071b72/issues/stoplightio/elements/1548?planning-poker)
