### ISSUE TITLE
Json Schema in markdown looks clunky

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1562]
There is no padding on the right of required:

![Screenshot 2021-07-06 at 11.55.03.png](https://images.zenhubusercontent.com/5f857aaa311cec7e20b4f258/26bad51a-5977-46dd-bb91-5d1cc6873f31)

It can also get awkwardly wide:

![Screenshot 2021-07-06 at 11.58.42.png](https://images.zenhubusercontent.com/5f857aaa311cec7e20b4f258/533d955a-a8f7-48c9-915a-d44574af078e)

**Comment by marcelltoth** [comment]
For now, we agreed to fix padding only.
