### ISSUE TITLE
Badge content appears shifted

### ISSUE THREAD

**Issue by mallachari** [stoplightio/elements#1568]
## Describe the bug

As mentioned in the comment https://github.com/stoplightio/elements/pull/1563#issuecomment-875485935 in some environments (browsers/zoom levels) mosaic badges content might appear shifted from the center position.

The goal of the issue is to check why does it happen, is it related to elements or mosaic and fix it if possible.

## To Reproduce

Open elements page with visible badges using different browsers and zoom levels.

## Expected behavior

Badges content is always centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/14196079/124766075-dfbf0d00-df36-11eb-8fe3-ec9f271ed2e6.png)
![image](https://user-images.githubusercontent.com/14196079/124766141-ee0d2900-df36-11eb-826b-cd04e91e3552.png)

**Comment by marcelltoth** [comment]
Try repo in Safari, zooming in via CMD++
