### ISSUE TITLE
Docs: Disambiguate Sceurity Schemes with same types

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1588]
## Use Story

As somebody describing an API with multiple security schemes using the same type, whether together or separately, I would expect them to be disambiguated so its clear to the user what badges are what. 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/67381/125072584-102fb400-e0bb-11eb-87a9-99efbfd8f4dc.png">

## Is your feature request related to a problem?

Calendly and Plaid have the issue where there are multiple security schemes that need disambiguation. 

Lets look at Plaid's example reduced to nothing.

```
openapi: 3.0.0
info:
  contact:
    name: Plaid Developer Team
    url: 'https://plaid.com'
  description: 'The Plaid REST API. Please see https://plaid.com/docs/api for more details.'
  termsOfService: 'https://plaid.com/legal/'
  title: The Plaid API
  version: 1.0.0
security:
  - clientId: []
    plaidVersion: []
    secret: []
tags:
  - description: The Plaid API
    name: plaid
paths:
  /accounts/balance/get:
    post:
      operationId: accountsBalanceGet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
 
components:
  securitySchemes:
    clientId:
      in: header
      name: PLAID-CLIENT-ID
      type: apiKey
    plaidVersion:
      in: header
      name: Plaid-Version
      type: apiKey
    secret:
      in: header
      name: PLAID-SECRET
      type: apiKey
```

## Describe the solution you'd like

Lets update the badge to contain the key that securityScheme was defined by (e.g.: `API Key (clientId)`, `API Key (plaidVersion)`, `API Key (secret)`). 

Also add this info on the overview page and security selector in try-it.

## Additional context

https://elements-demo.stoplight.io/?spec=https://api.apis.guru/v2/specs/plaid.com/2020-09-14_1.8.0/

**Comment by philsturgeon** [comment]
Link to feature: https://stoplightio.productboard.com/feature-board/planning/features/8608198

**Comment by mnaumanali94** [comment]
Don't show the scopes if we do.
