### ISSUE TITLE
Postman button isnt working in combination with webcomponent 

### ISSUE THREAD

**Issue by aparnakcvs** [stoplightio/elements#1589]
## Describe the bug

When we add below script that displays POSTMAN button to the page where web component is displayed.. It doesn't show button

<div class="postman-run-button custom" data-postman-action="collection/import" data-postman-var-1="07bdc50f90eb3b7fd20e">&nbsp;</div>
<script type="text/javascript">
  (function (p,o,s,t,m,a,n) {
    !p[s] && (p[s] = function () { (p[t] || (p[t] = [])).push(arguments); });
    !o.getElementById(s+t) && o.getElementsByTagName("head")[0].appendChild((
      (n = o.createElement("script")),
      (n.id = s+t), (n.async = 1), (n.src = m), n
    ));
  }(window, document, "_pm", "PostmanRunObject", "https://run.pstmn.io/button.js"));
</script>

## To Reproduce

1. Add the above script to html page where webcomponent is displayed
2. POSTMAN button is not displayed

## Expected behavior

POSTMAN button should display

**Environment :**
 - Drupal 8

**Comment by mnaumanali94** [comment]
@aparnakcvs Seems like you also need to add the button with the script as mentioned here: https://learning.postman.com/docs/publishing-your-api/run-in-postman/creating-run-button/#creating-a-run-in-postman-button

Button:
<div class="postman-run-button"
data-postman-action="collection/fork"
data-postman-var-1=":collection_id"
data-postman-collection-url=":collection_url"></div>


If it still doesn't work out, can you please share a HTML file to help us reproduce the issue 🙏

**Comment by aparnakcvs** [comment]
@mnaumanali94  - Button shows up when  I remove "elements-api" tag from html. Its issue with spotlight js script.. I have multiple JS scripts which doesnt work because of spotlight js

**Comment by philsturgeon** [comment]
@aparnakcvs could you provide us with enough HTML to make something reproduceable?

**Comment by mmiask** [comment]
<img width="1318" alt="Screen Shot 2021-07-15 at 10 55 30 AM" src="https://user-images.githubusercontent.com/58433203/125760140-60bb63d4-5ab7-4916-a410-6dc35131ce18.png">

@aparnakcvs I was able to add the button to a static html website, this might be Drupal-specific. As mentioned above - we'll need a more detailed steps to reproduce. How did you add both of these components to your website?

**Comment by aparnakcvs** [comment]
Yes- Its specific to Drupal. We added this  spotlight library in drupal theme.Once the js loads,other javascripts stops working.

**Comment by marcelltoth** [comment]
@aparnakcvs Can you provide us with a reproducible example then? e.g. an URL where this is broken, so we can check it out. It's really hard to figure out what's wrong when it's specific to your site we cannot see.

**Comment by aparnakcvs** [comment]
@marcelltoth - I have resolved this issue. Thank you! It was conflict with custom js+spotlight js
