### ISSUE TITLE
Incredibly long regex patterns need to be forcibly word wrapped

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1600]
## Describe the bug

Very very long validation properties like super-huge regex patterns are breaking display. 

![image](https://user-images.githubusercontent.com/67381/125694137-ab6af5c1-dfbc-4247-b0c5-9641406e627b.png)

## To Reproduce

https://learning.stoplight.io/docs/robotfactory/ZG9jOjYzMzI0-welcome#data-models

## Expected behavior

Break the line to the next line for match regex, and any other validations.

**Comment by mnaumanali94** [comment]
Happening again here for examples in platform:
![Screenshot 2021-08-17 at 10 00 41 PM](https://user-images.githubusercontent.com/17899454/129797975-fac440f4-70f8-4e6f-9b64-6061be65da4d.png)
