### ISSUE TITLE
Chore: use markdown component override provider for relative links

### ISSUE THREAD

**Issue by mmiask** [stoplightio/elements#1605]
## Summary

Follow-up to: #1598

> @marcelltoth @mmiask quick note - markdown-viewer has this sort of markdown component override provider built in now (stoplightio/markdown-viewer#95). Could switch to using it rather than the custom one here in elements, and get a nice code reduction win here. The one built into markdown-viewer also has benefit that the custom components will be leveraged even when markdown viewer is rendered in downstream components (for example markdown rendered in json schema viewer descriptions, etc).

**Comment by marcelltoth** [comment]
Get rid of our `MarkdownComponentProvider` (something like that) and just use MDV's.
