### ISSUE TITLE
PATCH is send as smaller case patch and results in a BAD_REQUEST

### ISSUE THREAD

**Issue by EugenMayer** [stoplightio/elements#1606]
Elements 7.0.2, stand alone variant from https://github.com/stoplightio/elements/tree/main/examples/static-html

When trying an PATCH endpoint, the request is set as patch `patch` smaller case. This leads to an BAD_REQUEST and violates the RFC (https://datatracker.ietf.org/doc/html/rfc7231#section-4.1)

This is only broken for the in browser fetch/xhr call, the preview curl request uses propere uppercase (and works in the cli). Using the same curl request with the smaller case `patch` fails on the cli with an 400 - so it is reproduceable.

Considered that all operations in openAPI are smaller case in the spec, this cannot be a declaration issue on our side, right. It must be a mapping glitch AFAIU.

**Comment by mmiask** [comment]
Hey @EugenMayer! Thanks for reporting this one. It indeed looks like something we could improve upon. We'll keep you updated if this changes status. Also, thank you for a precise description, it helps a lot! 🙏

**Comment by EugenMayer** [comment]
Thanks!

**Comment by EugenMayer** [comment]
How to follow the release process to understand when this is released?
