### ISSUE TITLE
Always show the overview

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#1615]
Currently we only show overview page if a description exists. This leads to a few concerns:
- The navigation changes
- No way to easily copy baseurl / mockurl
- No way for users to know the overview page even exists

Let's show the overview page always irrespective of the description/summary being there or not.

This applies to both elements standalone and in platform.

**Comment by mpodlasin** [comment]
The page without description does look very, very empty - borderline broken.

I would advocate for having some placeholder content there.

Maybe even something as simple as:

"This API doesn't have any description."

Or maybe @noor-ahmad can help us here. (Ignore other quirks in the screenshot - it's an old one)

![Screenshot 2021-07-05 at 15.14.58.png](https://images.zenhubusercontent.com/5f857aaa311cec7e20b4f258/58a088a0-15ce-4d88-a9b2-97e987a0d001)
