### ISSUE TITLE
Show the URLs / Auth Info in the middle on the overview page

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#1616]
Currently we show the URL info and Auth info on the right side of the overview page. This makes for a very blank overview page in case of empty /small descriptions. 

Let's move the URLs / Auth Info in the middle on the overview page.

The structure should look like this:
- Title / Badges
- URLs / Auth Info
- Description

Additional Info:
- Make the panels wide to reflect the width of the markdown content

**Comment by marcelltoth** [comment]
@mnaumanali94 Can you discuss this with @noor-ahmad and come up with a conclusion?
