### ISSUE TITLE
Send Request: File picker doesn't show up for a multipart/form-data request with a binary format field

### ISSUE THREAD

**Issue by fedemar** [stoplightio/elements#1649]
## Describe the bug

File picker doesn't show up for a multipart/form-data request with a binary format field.

## To Reproduce

Setting the following requestBody does not render a file picker and doesn't show the custom header in the request sample.
```
requestBody:
    content:
        multipart/form-data:
            schema:
                type: object
                properties:
                    metadata:
                        type: string
                        description: Image metadata.
                    image:
                        type: string
                        format: binary
                        description: Binary format of media to be uploaded.
            encoding:
                image:
                    contentType: image/png, image/jpeg
```
## Expected behavior

A file picker should be displayed instead of a text input.
![image](https://user-images.githubusercontent.com/5452635/127074405-d81f10f4-9416-4c65-82bb-2d5136bb3ae8.png)

The custom header should be shown in the request sample.
![image](https://user-images.githubusercontent.com/5452635/127075458-e24b3203-d227-43af-b5da-c149dbfd6d80.png)

Am I missing something when defining the requestBody?
How would you go about defining a multipart/form-data requestBody with a binary format field?

**Comment by mallachari** [comment]
Thanks for reporting! Looks like request samples are indeed not showing correctly in that case. Though I can't reproduce the file picker issue. Could you show how it looks on your side? Using your example I can see the file picker:
<img width="264" alt="Screenshot 2021-07-28 at 09 26 25" src="https://user-images.githubusercontent.com/14196079/127282447-4265e64b-f653-46eb-bd20-08808b730dfe.png">

Which version of elements are you using? Could you share whole API document example?

**Comment by fedemar** [comment]
Hey mallachari, thanks for replying.

Here's how it looks from my side

![image](https://user-images.githubusercontent.com/5452635/127416804-b2999903-aefe-4564-809f-e69e5eb237b2.png)

I'm using beta, what version should I use?

```
<script src="https://unpkg.com/@stoplight/elements@beta/web-components.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@stoplight/elements@beta/styles.min.css">
```

Thanks!

**Comment by mallachari** [comment]
There's the latest stable release of elements (7.0.5) that you could use. Let me know how if that makes it work. If not I'll try to reproduce it.

**Comment by fedemar** [comment]
Still not showing the file picker.

Here's the specification
```
openapi: 3.0.0
info:
    title: Some API
    description: This is a description
    contact:
        email: some@email.com
    version: 1.0.0
servers:
    - url: '/v1/api'
      description: Develop
tags:
    - name: media
paths:
    /media:
        post:
            operationId: create_media
            tags:
                - media
            summary: Create media
            security:
                - API Key: []
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                metadata:
                                    type: string
                                image:
                                    type: string
                                    format: binary
                        encoding:
                            image:
                                contentType: image/png, image/jpeg
            responses:
                '200':
                    description: |
                        Media created successfully.
                    content:
                        application/json:
                            schema:
                                type: string
components:
    securitySchemes:
        API Key:
            name: x-api-key
            type: apiKey
            in: header
security:
    - API Key: []
```

And here's the html
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link type="image/ico" href="/favicon.ico" rel="icon">
    <title>Calibration API Spec</title>
    <script src="https://unpkg.com/@stoplight/elements@7.0.5/web-components.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/@stoplight/elements@7.0.5/styles.min.css">
  </head>
  <body>

    <elements-api
      apiDescriptionUrl="/openapi/specification2.yaml"
      router="hash"
      layout="sidebar"
    />
  </body>
</html>
```

Thanks!
