### ISSUE TITLE
Request maker body and sample should have a max height

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#1664]
The body in request maker should have a max height much like response example. This should be both in reference and embedded markdown

To replicate:
1. Go here: https://schoolyear.stoplight.io/docs/schoolyear-api-docs/b3A6OTM2NTkyMQ-create-new-exam
2. Run `__SL.state.flags.enabledFlags.elements_v7 = true` in console

![Screenshot 2021-08-03 at 4.46.12 PM.png](https://images.zenhubusercontent.com/5ea9a7f489044245dbd23d46/8fae6baa-4ffd-464e-a766-350be5337e4a)

**Comment by paulatulis** [comment]
Hmmm I am trying to reproduce this locally and cannot... am I looking at the wrong component?

![2021-08-19 15.20.33.gif](https://images.zenhubusercontent.com/5dc060647a4d02000177a6d0/d8558935-93da-43cb-b055-05ed9953c7c2)

**Comment by mnaumanali94** [comment]
Markdown Try-it has it for sure. This was fixed in some other PR i guess.

**Comment by paulatulis** [comment]
Is it alright if I go ahead and close this issue in that case?
