### ISSUE TITLE
elements-web-components

### ISSUE THREAD

**Issue by VenkatGarlapati** [stoplightio/elements#1674]
It seems like [@stoplight/elements](https://www.npmjs.com/package/@stoplight/elements) and [@stoplight/elements-web-components](https://www.npmjs.com/package/@stoplight/elements-web-components) not in sync.

When can we expect the new version of web components in npm? 
If this is not the right package to install for the web components, Is there any other package to install web components using NPM

**Comment by philsturgeon** [comment]
@VenkatGarlapati the @stoplight/elements-web-components package is discontinued as the web components were moved over to @stoplight/elements. Check out the docs to see how you can use it: https://meta.stoplight.io/docs/elements/ZG9jOjEyMDU2Njg0-web-component
