### ISSUE TITLE
Trying to load Elements in local connecting to my project id

### ISSUE THREAD

**Issue by subalalithafl** [stoplightio/elements#1690]
## Describe the bug

Getting not found when trying to connect to my project when using react app for portal. I am in Starter plan

## To Reproduce

1. Created a react project using the command npx create-react-app my-dir --template @stoplight/elements-dev-portal
2. Edited the project id to reflect my project id as mentioned in the doc in the file App.js
3. Yarn start

## Expected behaviour

My project docs displayed as it did with the example project.

**Screenshots**
![Screenshot from 2021-08-15 19-02-27](https://user-images.githubusercontent.com/79745769/129480316-b696aba6-fb3e-4411-a5b9-fb146fd5bd68.png)

**Comment by paulatulis** [comment]
Hi @subalalithafl, are you able to confirm you're using your own public, published project id? You can find it by going to the project settings page (your project id will be unique to your project)
![Screen Shot 2021-11-17 at 2 02 14 PM](https://user-images.githubusercontent.com/47359669/142273906-8aba3977-ed20-4b56-8d59-fddd3b86f2a5.png)

**Comment by subalalithafl** [comment]
Yes, I was using my project ID. Just an update, I for now dropped using portal and using plain elements now.

**Comment by mnaumanali94** [comment]
Do you have zip file you can share potentially?

**Comment by subalalithafl** [comment]
@mnaumanali94 Unfortunately no. This was 3 months back. I switched to normal Elements. But i remember i did not do anything special. I just followed the steps in the doc. I created the project and changed only the project id as mentioned in the issue description. I changed nothing else.

**Comment by mnaumanali94** [comment]
@subalalithafl We closed this as we were unable to replicate this on our side. Please feel free to reopen this issue, if you see the issue again.
