### ISSUE TITLE
Try-it copy options

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#1722]
Add a copy button on response examples

![Screenshot 2021-08-25 at 6.16.30 PM.png](https://images.zenhubusercontent.com/5ea9a7f489044245dbd23d46/df6bf181-0817-4e93-9949-7a060a613798)

Add a copy button beside path

![Screenshot 2021-08-25 at 6.17.16 PM.png](https://images.zenhubusercontent.com/5ea9a7f489044245dbd23d46/c0628f13-0529-4846-ae7d-aa93b35efb48)

**Comment by mnaumanali94** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Pierogi-Platoon-610871b8d6e5310013071b72/issues/stoplightio/elements/1722?planning-poker) with ZenHub @wmhilton @paulatulis @domagojk @mpodlasin @mmiask @mallachari

**Comment by mnaumanali94** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Pierogi-Platoon-610871b8d6e5310013071b72/issues/stoplightio/elements/1722?planning-poker) with ZenHub @domagojk @mallachari @mmiask @paulatulis @wmhilton @mpodlasin @Nezteb

**Comment by mpodlasin** [comment]
Should be added here

https://github.com/stoplightio/elements/blob/main/packages/elements-core/src/components/ResponseExamples/ResponseExamples.tsx

and here

https://github.com/stoplightio/elements/blob/main/packages/elements-core/src/components/ResponseExamples/ResponseExamples.tsx
