### ISSUE TITLE
Missing array enum item definitions in query parameters

### ISSUE THREAD

**Issue by pelzhaus** [stoplightio/elements#1750]
## Describe the bug

Enums items of arrays in query parameters are not rendered correctly. This is related to https://github.com/stoplightio/elements/issues/1665 but now only appearing in query parameters.

I believe this is the right repo to post in, but if not let me know where I can add this!

## To Reproduce

Given this OpenAPI path parameters:
```json
        "parameters": [
          {
            "description": "An array query parameter",
            "in": "query",
            "name": "enum_array",
            "required": false,
            "schema": {
              "description": "An array query parameter",
              "items": {
                "enum": [
                "foo",
                "bar"
                ],
                "type": "string"
              },
              "type": "array"
            }
          }
	    ]
```
In the old-UI Stoplight, this is rendered as:
![image](https://user-images.githubusercontent.com/12112738/132413828-8c1d7cc7-b83b-4aad-a955-16779d8b474f.png)

In the new-UI Stoplight, this is rendered as:
![image](https://user-images.githubusercontent.com/12112738/132414091-b9131db4-7e77-481a-b5dd-2f7304072f5e.png)

## Expected behavior

I would expect the rendering to look just like body array enums, with `array[string]` description and allowed values:
![image](https://user-images.githubusercontent.com/12112738/132416315-1f052d70-7449-4a14-baa6-fc2e80d3b902.png)

## Additional context

**Screenshots**
See above

**Environment (remove any that are not applicable):**
 - Library version: ???
 - OS: macOS catalina 10.15.6
 - Browser: Chrome 92.0.4515.159
 - Platform: web

**Comment by rawbee** [comment]
+1

**Comment by awendland** [comment]
Having full type information displayed for our query parameters in endpoint docs is important to ensure our customers know how to interface with the API correctly. We're blocked on upgrading to the new UI by this. Thanks for the progress made on #1665 already!
