### ISSUE TITLE
File upload Content-Type header is missing boundary parameter

### ISSUE THREAD

**Issue by kristjanpeterson1** [stoplightio/elements#1751]
## Describe the bug

multipart/form-data requests with are missing "boundary" in the Content-Type header

## To Reproduce

1. Given this OpenAPI document '
`{
  "openapi": "3.0.2",
  "info": {
    "title": "Example",
    "description": "Description",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost"
    }
  ],
  "paths": {
    "/upload_file": {
      "post": {
        "tags": [],
        "summary": "Upload file",
        "operationId": "upload_file",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "title": "title",
                "required": [
                  "file"
                ],
                "type": "object",
                "properties": {
                  "file": {
                    "title": "File",
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {}
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  }
}`
'
2. The generated request "Content-Type" header is just "multipart/form-data"

## Expected behavior

The "Content-Type" request header should include the "boundary=----" parameter after "multipart/form-data"

**Screenshots**
![example](https://user-images.githubusercontent.com/26324758/132504136-a278df02-ea32-47d2-851b-5b1abb6569b4.png)

Example shows its trying to put the boundary parameter in the header

**Environment (remove any that are not applicable):**
 - Browser: Firefox 91.0.2 or Chrome 93.0.4577.63
 - Platform: web

**Comment by JohannesTK** [comment]
@mnaumanali94, thanks for assigning. This seems like a high priority because it means all the multipart/form-data end-points interactive examples for all of your clients are broken? We have already lost over 30+ devs because of that (we are still a small startup). Thanks.

**Comment by mallachari** [comment]
@kristjanpeterson1 @JohannesTK the fix is included in the latest elements release (7.3.4).

**Comment by JohannesTK** [comment]
@mallachari excellent to hear, thanks! When will it be pushed to the hosted API docs platform?

**Comment by mallachari** [comment]
It should already be available on the platform.

**Comment by kristjanpeterson1** [comment]
Yep, thanks a lot!
