### ISSUE TITLE
Mocking errors are not formatted

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1795]
## Describe the bug

We "prettify" JSON when its a response, but it looks like mocking errors are coming out on a single line. 

## To Reproduce

1. Send an invalid request to any spec with mocking enabled
2. See unprocessable entity but squished in one line of JSON

## Expected behavior

All responses should be formatted consistently regardless of mocking or "real servers", so this should be expanded to multiple lines, indented, etc.

**Screenshots**

<img width="460" alt="Screen Shot 2021-10-01 at 10 55 08 AM" src="https://user-images.githubusercontent.com/67381/135602006-2d83a435-99d3-49b5-98bf-e3366b1cb6a8.png">

**Environment (remove any that are not applicable):**
 - Library version: hosted elements but probably also devportal
 - OS: macOS
 - Browser: Firefox 91.0.1

**Comment by mpodlasin** [comment]
https://github.com/stoplightio/elements/blob/main/packages/elements-core/src/components/TryIt/TryIt.tsx#L171 Here is where the failed responses are handled.

**Comment by jgreen44** [comment]
This seems to be working already.
https://images.zenhubusercontent.com/184680614/de250c18-35df-4ba6-a74b-154d05e6f947/issue1795.mov
