### ISSUE TITLE
Elements does not include the Accept request header

### ISSUE THREAD

**Issue by Linuus** [stoplightio/elements#1798]
## Describe the bug

In OpenAPI the `Accept` _request_ header is defined by `responses.<code>.content.<media-type>`. When making a request from the Elements app, it doesn't add this `Accept` header.

## To Reproduce

Given this OpenAPI document:

```yaml
---
openapi: 3.1.0
info:
  version: 1.0.0
  title: Test
servers:
- url: http://localhost:3000
  description: Development
paths:
  "/foobars":
    get:
      operationId: fetchFoobars
      summary: Fetch foobars
      tags:
      - Foobars
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  title: Foobar
                  properties:
                    id:
                      type: integer
                      description: The ID of the Foobar
                  required:
                  - id
                  additionalProperties: false
```

The Elements app is generating this request:

```sh
curl --request GET \
  --url http://localhost:3000/foobars \
  --header 'Content-Type: application/json'
```

Here we can see that the `Content-Type` header is set but not the `Accept` header.

## Expected behavior

I expect the request to include the `Accept` header:

```sh
curl --request GET \
  --url http://localhost:3000/foobars \
  --header 'Content-Type: application/json'
  --header 'Accept: application/json'
```

**Comment by philsturgeon** [comment]
Absolutely, we should be doing this! In open-source october we're donating 400 trees for each pull request sent so this would be an ideal time to do it: https://hackernoon.com/stoplights-open-source-october-hacktoberfest-involvement-and-pull-requests-for-trees

We don't really need to be setting Content-Type when there's no body either, so if somebody gets into that bit of the code it would be great to knock out both issues. If you submit it as two pull requests that's 800 trees! 🌳 🙌
