### ISSUE TITLE
x-internal operations are still visible on documentation

### ISSUE THREAD

**Issue by rolivares** [stoplightio/elements#1805]
## User story.

As an API designer role person I want to mark certain operations as internally visible in order to hide those operations from public display on documentation

## Is your feature request related to a problem?

Compatibility problem related to documentation consistency

## Describe the solution you'd like

When I'm using stoplight as publishing platform is posible to me acomplish this using the extended property "x-internal", so it would nice that Webcomponent would to have the same behavior

**Comment by chohmann** [comment]
Fix released in 7.3.8
