### ISSUE TITLE
File Upload button not working properly. Some seconds after selecting some file to upload, Send Request form is being erased suddenly

### ISSUE THREAD

**Issue by manuelfhp** [stoplightio/elements#1808]
## Describe the bug

File Upload button not working properly. Some seconds after selecting some file to upload, Send Request form is being erased suddenly

## To Reproduce

1. Given this OpenAPI document 
you can download the openAPI document or use the URL to try it online: 
https://www.pfx.com.br/openapi.yaml
https://elements-demo.stoplight.io/?spec=https://www.pfx.com.br/openapi.yaml#/operations/files/create

3. See error
In Endpoints > File > Create , just fill the Send Request form and select some file to upload
Some seconds after select some file, all the form will be erased.

## Expected behavior
The SendRequest form should keep with the selected/informed values. Otherwise you cannot send a request because all fields are empty, including the file uploaded.

## Additional context
We reproduced this problem in Stoplight Elements Embed via Web Component.
In the stoplight demo website the problem occurs:
https://elements-demo.stoplight.io/?spec=https://www.pfx.com.br/openapi.yaml#/operations/files/create

**Screenshots**
![CleanShot 15-10-2021 as19 54 47](https://user-images.githubusercontent.com/1836248/137562578-d0abf87c-c9dc-4a4a-b391-312d616873f0.png)
![CleanShot 15-10-2021 as19 55 56](https://user-images.githubusercontent.com/1836248/137562640-deae90d0-6849-4a51-af92-bf77e34708b0.png)

**Environment (remove any that are not applicable):**
 - OS: [OSX 11.6 BigSur]
 - Browser: [Chrome 94.0]
 - Browser: [Safari 15.0]
 - Platform: [Stoplight Elements Embed via Web Component]
 https://elements-demo.stoplight.io/?spec=https://www.pfx.com.br/openapi.yaml#/operations/files/create

**Comment by chohmann** [comment]
as discussed on our call today @mpodlasin is going to take this issue over as it looks like it's related to some core infrastructure for elements. He's better equipped to make the call on what to do based on his investigation. Re-assigning ticket to him.
