### ISSUE TITLE
Cannot find module 'lodash/fp'?

### ISSUE THREAD

**Issue by solo-xwz** [stoplightio/elements#1809]
## Additional context
As long as I import API components (`import {API} from "@stoplight/elements";`) in react, will this error occur?

**Screenshots**
![image](https://user-images.githubusercontent.com/89335154/137575675-9da43cdb-68d5-41f1-b66d-2b068d7b5f9e.png)

**Environment (remove any that are not applicable):**
 - Library version: 7.3.7
 - OS: Windows 10
 - Browser: Chrome 94
 - Platform: web

**Comment by mmiask** [comment]
@solo-xwz We've removed the `fp` modules in the latest release of Elements. Please update and let us know if it's still happening for you :)
