### ISSUE TITLE
Incorrect submenu item placement

### ISSUE THREAD

**Issue by itsmewes** [stoplightio/elements#1812]
## Describe the bug

When adding the Stoplight Elements web component to a page and is nested in other elements, and the other elements are set to `position:relative` and the layout is set to sidebar then the second level of the dropdown seems to have a top that has a ceiling on it that stops it from matching the top level language names. This only happens when the surrounding layout is set to `position:relative` when changed to `position:initial` the dropdown works as expected.

## To Reproduce

1. Add Stoplight Elements via the web component to a page where the web component is nested inside other nodes.
2. Make the surrounding nodes have a position of relative.
3. View in the browser  and scroll down to the Request sample dropdown and choose a language near the top of the list.

## Expected behavior

That the second level of the language dropdown to be inline with the first level.

## Additional context

Just that the positioning makes a difference.

**Screenshots**

https://user-images.githubusercontent.com/974222/137858865-ebb694db-ac92-4787-979c-8007cbdfb50a.mp4

**Environment (remove any that are not applicable):**

 - Library version: 7.3.7
 - OS: macOS Big Sur
 - Browser: Firefox 93
 - Platform: Desktop

**Comment by philsturgeon** [comment]
Thanks for reporting this and providing a view @itsmewes, this is brilliant to see such a customised version of Elements in the wild. 

@mnaumanali94 could you see what might be going on here? Is this some weird CSS conflict perhaps?
