### ISSUE TITLE
x-doc-hide : true not working after migration from next to studio - URGENT

### ISSUE THREAD

**Issue by smitabh84** [stoplightio/elements#1919]
## Describe the bug

We migrated a lot of projects from Next to Studio and the APIs having 

 "x-private": true, 
 "x-doc-hide": true, 

which were hidden before and showing up in the published document after migration.

Please help urgently.

## To Reproduce

1. Given this OpenAPI document '...'
2. Run this CLI command '....'
3. See error

## Additional context

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]
 - Platform: [desktop or web]

**Comment by mnaumanali94** [comment]
Hey! If you're looking to hide endpoints/models you can use `x-internal:true` for that.

**Comment by smitabh84** [comment]
Hi Nauman,

This is something new to Studio? we have been using x-doc-hide and x-private in all our legacy API definitions and after Next to Studio migration, this should stay the same. We need to make a lot of changes if we need to introduce a new parameter now. 

Why was this changed from x-doc-hide to x-internal? Is there a workaround to make this work as it is?
