### ISSUE TITLE
Try It: allowed value dropdown funny behavior with a 0

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1959]
## Describe the bug

When the first value in an enum is 0 its asking you to pick an option but 0 is already picked, but it doesn't think its a value? 

## To Reproduce

1. Given this OpenAPI demo https://elements-demo.stoplight.io/?spec=https://members-api.parliament.uk/swagger/v1/swagger.json#/paths/api-Location-Browse-locationType---locationName/get
2. Try and use the location type in the try it
3. See error

## Expected behavior

I'd expect to see 0 selected in the dropdown, because its required. If it was optional, I'd expect to see "select an option".

**Screenshots**

https://user-images.githubusercontent.com/67381/148088560-6a778cf5-e098-4e3e-8ff6-10fdcade9445.mov

**Environment (remove any that are not applicable):**
 - OS: macOS
 - Browser: Firefox 95.0.2 (64-bit)
 - Platform: web

**Comment by mnaumanali94** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Pierogi-Platoon-610871b8d6e5310013071b72/issues/stoplightio/elements/1959?planning-poker) with ZenHub @mallachari @mmiask @mpodlasin @Nezteb @paulatulis @wmhilton @domagojk
