### ISSUE TITLE
Server URL with :80 in it won't work

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1960]
## Describe the bug

A :80 is appearing in the URL of an OAS2 document which doesn't seem to define it anywhere.

## To Reproduce

1. Given this OpenAPI document https://commonsvotes-api.parliament.uk/swagger/docs/v1
2. Load up elements (happens in the demo) https://elements-demo.stoplight.io/?spec=https://commonsvotes-api.parliament.uk/swagger/docs/v1
3. See :80 in the server URL

## Expected behavior

The :80 should be gone.

If I try it with curl, with :80 will fail and without will work: 

```
$ curl -X GET --header 'Accept: application/json' 'https://commonsvotes-api.parliament.uk:80/data/divisions.json/groupedbyparty'
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

**Screenshots**

<img width="705" alt="Screen Shot 2022-01-04 at 5 24 18 PM" src="https://user-images.githubusercontent.com/67381/148099187-d8998697-d3f1-4091-b41d-e70325007c3b.png">
<img width="866" alt="Screen Shot 2022-01-04 at 5 24 23 PM" src="https://user-images.githubusercontent.com/67381/148099191-13f118a9-fc4a-4865-af86-d5d81574b30e.png">

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]
 - Platform: [desktop or web]

**Comment by mnaumanali94** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Pierogi-Platoon-610871b8d6e5310013071b72/issues/stoplightio/elements/1960?planning-poker) with ZenHub @mallachari @mmiask @mpodlasin @Nezteb @paulatulis @wmhilton @domagojk

**Comment by kaylachun** [comment]
![image.png](https://images.zenhubusercontent.com/62361f27b082a7927b8dbe87/ef3bad77-138f-4613-81b4-ea98fc6f3150)

**Comment by kaylachun** [comment]
Error is coming from the Stoplight cors proxy server itself.
