### ISSUE TITLE
Scroll table of contents separate from body

### ISSUE THREAD

**Issue by richard-rance** [stoplightio/elements#1963]
## User story.

As a public page browser of a site using the elements dev portal, I would like to scroll the table of contents independently of the body, so that I can quickly jump to the next page or another header on the current page.

## Is your feature request related to a problem?

From one of my users 
> It makes navigation of the guides very frustrating, losing all navigation after scrolling, and having to scroll back up to the top.

## Describe the solution you'd like

When using the hosted version of Stoplight Studio the 3 sections scroll independently. I would like the same to happen on self hosted sites.

[Example hosted version](https://vendasta.stoplight.io/docs/openapi-specs/ZG9jOjEzMTU1Mjky-create-business-users) 
![image](https://user-images.githubusercontent.com/6698651/148414565-bfa68ea4-683b-43e0-aa5a-ee87f1ad5c5c.png)

[Example self hosted version](https://developers.vendasta.com/platform/ZG9jOjEzMTU1Mjky-create-business-users)
![image](https://user-images.githubusercontent.com/6698651/148415015-1e705d55-9a51-4453-989e-c04d8cef3ed0.png)

## Additional context

[PagerDuty](https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTY5-register-an-app), which was recently featured in the Stoplight blog, also has the same issue with scrolling so I don't think this is a misconfiguration on my part.

**Comment by mnaumanali94** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-Pierogi-Platoon-610871b8d6e5310013071b72/issues/stoplightio/elements/1963?planning-poker) with ZenHub @mallachari @mmiask @mpodlasin @Nezteb @paulatulis @wmhilton @domagojk

**Comment by mpodlasin** [comment]
Hello. Just follow this guide: https://meta.stoplight.io/docs/elements/ZG9jOjE0NzU0NTA1-layouts

Closing for now, but feel free to ask further questions in this issue.
