### ISSUE TITLE
Internal links are broken

### ISSUE THREAD

**Issue by fsargent** [stoplightio/elements#1969]
## Describe the bug

Internal links (links between items in Stoplight) are broken, and instead show as just links to the current page. 

## To Reproduce

1. Link between one document and another in Stoplight
2. Render using Stoplight Elements
3. Link will show current URL not the destination URL

In Stoplight studio the link will be `{correctURL}undefined` which might be a hint as to what is happening.

## Expected behavior

Expected behavior is for the link to be converted to the appropriate URL from the stoplight internal reference schema.

![image](https://user-images.githubusercontent.com/273880/148982528-18618652-56f2-49a3-9a0b-2bccfb88eca8.png)
![image](https://user-images.githubusercontent.com/273880/148982789-c544d88b-3a95-4e03-a53f-e1fcff50ccf6.png)
![image](https://user-images.githubusercontent.com/273880/148983124-d0ce0dfb-6561-4bf4-8bcb-cb1b0f1af4b6.png)

gz#7708<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/7708'>Zendesk ticket #7708</a>)</i>

**Comment by fsargent** [comment]
@wmhilton How can we use the latest version which includes this fix? Will there be a release to NPM today?

**Comment by fsargent** [comment]
@wmhilton @raleigh04 After upgrading I'm now seeing this issue when clicking the URL:
![image](https://user-images.githubusercontent.com/273880/149992672-f8972c7b-9c05-4e24-9d7a-b1dc982ef28d.png)

**Comment by wmhilton** [comment]
> @wmhilton @raleigh04 After upgrading I'm now seeing this issue when clicking the URL: ![image](https://user-images.githubusercontent.com/273880/149992672-f8972c7b-9c05-4e24-9d7a-b1dc982ef28d.png)

Oh hmm! Can you open a new issue for that? I'm not able to reproduce it.

**Comment by fsargent** [comment]
@wmhilton https://github.com/stoplightio/elements/issues/1980
