### ISSUE TITLE
API reference page is not rendering

### ISSUE THREAD

**Issue by smitabh84** [stoplightio/elements#1970]
## Describe the bug

Nutanix Prismv3 project at - https://nutanix.stoplight.io/docs/prismv3-final3/YXBpOjI1NTg1NDQz-api-reference is not rendering the page. The user cannot export the [API] if this is not resolved.

![image](https://user-images.githubusercontent.com/66934062/149285319-875791ee-faad-47ab-9e5f-cde23cca1b6e.png)

## To Reproduce

1. Given this OpenAPI document '...'
2. Run this CLI command '....'
3. See error

## Additional context

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: [e.g. 3.0.0]
 - OS: [e.g. Windows 7]
 - Browser: [e.g. Chrome 61]
 - Platform: [desktop or web]

**Comment by smitabh84** [comment]
Can someone look into it?

**Comment by mpodlasin** [comment]
<img width="775" alt="Screenshot 2022-01-18 at 14 48 29" src="https://user-images.githubusercontent.com/7916523/149949527-53a2e787-7032-43c6-820d-3c865980f896.png">

Hey. It would appear that a server url is malformed? 🤔  I would be curious what you see in the forms during editing the API.

**Comment by smitabh84** [comment]
Thanks. Fixed it now.
