### ISSUE TITLE
Page scrolling not working

### ISSUE THREAD

**Issue by brunobarretofreitas** [stoplightio/elements#1997]
## Describe the bug

It's not being possible to scroll the documentation

## To Reproduce

We can see this error at the demo page:
https://elements-demo.stoplight.io/?_ga=2.152868987.317374460.1643205595-1923601167.1643205595#/operations/get-todos-id

## Expected behavior
It should be possible to scroll over the documentation.

**Environment (remove any that are not applicable):**
 - Library version: https://unpkg.com/@stoplight/elements/web-components.min.js
 - OS: Mac OS Monterey 12.1
 - Browser: Safari
 - Platform: Web

**Comment by hampuskraft** [comment]
This is what caused it, reverting this change does not seem to cause any issues for me, however: https://github.com/stoplightio/elements/commit/efb3474327bb6f06a47b3dee32c733a1bfc5e457#diff-71b63e547e9d97b42c98cf1725995661bb2db4002a957290d9b5b5c8a620aca0L43.
