### ISSUE TITLE
Oauth Authorization token defaults to undefined

### ISSUE THREAD

**Issue by Thomasdezeeuw** [stoplightio/elements#2037]
## Describe the bug

Request sample sometimes contain an undefined token.

## To Reproduce

1. Open a spec with Oauth security and open a page that requires it. For example: https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/digitalocean/openapi/main/specification/DigitalOcean-public.v2.yaml#/operations/install_kubernetes.
2. Look at "Request Sample" in the right bar.
3. The token value will be `undefined` for the Authorization header, i.e. `"Authorization": "Bearer undefined"`. 

## Expected behavior

Expected at least a value. A clear indication that an authorization token is needed would be nice, for example `$TOKEN`. Or a more complex fix perhaps even a language specific variable.

**Comment by mnaumanali94** [comment]
It should be empty `Bearer `.  Shouldn't show up as undefined.

**Comment by ColmanHumphrey** [comment]
I'd love to be able to supply the placeholder as part of the props in the web component (with a sensible default, like the empty space per @mnaumanali94). If it's too small a feature for its own prop, maybe it can be part of a more general `options` prop or similar.

**Comment by saper** [comment]
![digitalocean-token-auth-bug-2037](https://github.com/stoplightio/elements/assets/248374/566dccbe-4ea4-437f-8b43-71b4e31486c2)

As of 19e1ae93d2ddfa3000474838aba0de45188d028f does not seem to be the case...

**Comment by Thomasdezeeuw** [comment]
Can confirm it doesn't show `undefined` any more. Thanks @saper.
