### ISSUE TITLE
not able to load the home page after edit - https://www.nutanix.dev/api_references/move/#/7YItQxTyEW-Kth0rDHd2s-index

### ISSUE THREAD

**Issue by smitabh84** [stoplightio/elements#2107]
## Context
I edited the home page and published it. now I am unable to load the index.md on our portal.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by mnaumanali94** [comment]
@smitabh84 

https://www.nutanix.dev/api_references/move/#/ZG9jOjQ1Mg-index

This seems to be the correct link and it loads fine. Anything we are missing here?

**Comment by smitabh84** [comment]
Not sure what made it work. thanks anyways.
