### ISSUE TITLE
Integration error w/Stoplight and Docusaurus

### ISSUE THREAD

**Issue by caitlinnew** [stoplightio/elements#2135]
Our documentation website is currently making use of docusaurus and we are trying to integrate stoplight into our website for API documentation. On integrating stoplight with our codebase we get the following error

"Module not found: Error: Can't resolve './dist/abort-controller' Did you mean 'abort-controller.mjs'?"

## Context
Our docs are on docusaurus and we tried integrating stoplight elements with docusaurus. We have the api definition file (yml) and also installed the necessary node packages. 

We created a JS file and added the stoplight-elements react component to it.

Our JS file looks similar to this https://github.com/dyte-in/docs/blob/main/src/pages/api.jsx
On running and building the app we get the following error

"Module not found: Error: Can't resolve './dist/abort-controller' Did you mean 'abort-controller.mjs'?"

## Current Behavior
![image](https://user-images.githubusercontent.com/92755071/165139362-dbcd95b6-30da-4e96-8198-25fc059fbfa6.png)

gz#9362<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/9362'>Zendesk ticket #9362</a>)</i>

**Comment by kushv16** [comment]
This is our docs repo: https://github.com/symblai/symbl-docs

and this is the branch where we attempted stoplight-docusaurus integration: https://github.com/symblai/symbl-docs/tree/api-playground-using-stoplight

**Comment by jasikpark** [comment]
https://stackoverflow.com/questions/74876229/how-to-tweak-docusaurus-webpack-config-for-some-react-component

++ would be great to have an elements-docusaurus-plugin package

**Comment by jasikpark** [comment]
```
core.esm.js?b97d:5645 Uncaught (in promise) ReferenceError: process is not defined
    at eval (core.esm.js?b97d:5645:1)
    at ./node_modules/@stoplight/mosaic/core.esm.js (vendors-node_modules_stoplight_elements_index_mjs.js:1566:1)
    at __webpack_require__ (runtime~main.js:36:33)
    at fn (runtime~main.js:356:21)
    at eval (index.mjs:49:76)
    at ./node_modules/@stoplight/elements-core/index.mjs (vendors-node_modules_stoplight_elements_index_mjs.js:8110:1)
    at __webpack_require__ (runtime~main.js:36:33)
    at fn (runtime~main.js:356:21)
    at eval (index.mjs:5:83)
    at ./node_modules/@stoplight/elements/index.mjs (vendors-node_modules_stoplight_elements_index_mjs.js:8118:1)
```

**Comment by jasikpark** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/10626596/214703365-5dd6db92-f110-4b0f-bf43-09d732b1839e.png">

ah, does this tool not support webpack 5 then?

**Comment by liuxueyong123** [comment]
I resloved this problem by node-polyfill-webpack-plugin

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
