### ISSUE TITLE
Servers dropdown labels harm UX

### ISSUE THREAD

**Issue by pepawel** [stoplightio/elements#2147]
As a API consumer I would like to see what API server is selected. Currently I can't, because instead of server description I see title of OpenAPI document. I need to click on the dropdown which shows shows server descriptions as secondary labels.

You can see the issue here:
https://elements-demo.stoplight.io/?spec=https://api.apis.guru/v2/specs/linode.com/4.97.2/openapi.yaml#/operations/getAccount

![screenshot-elements-demo stoplight io-2022 05 16-15_38_13](https://user-images.githubusercontent.com/64653/168605766-725651cf-0d13-444f-840f-94bd04e496bd.png)

**Comment by mnaumanali94** [comment]
Being fixed in #2318
