### ISSUE TITLE
Wrong order of additional model property in case of inheritance

### ISSUE THREAD

**Issue by jschaefer77** [stoplightio/elements#2150]
I have three simple models (CompA, CompB and CompC).

CompB inherits all from CompA, CompC inherits from CompB.
For the sake of simplicity CompB and CompC each extend the inherited model by only one property.

## Current Behavior
For CompC the property "testC" is rendered first, while e.g. for CompB the property "testB" was added to the end.

## Expected Behavior
As CompB simply adds the addtional property to the end, CompC should do the same.

## Possible Workaround/Solution
none

## Steps to Reproduce
openapi: 3.0.0
info:
  title: PolyTest
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/comps/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CompA'
                  - $ref: '#/components/schemas/CompB'
                  - $ref: '#/components/schemas/CompC'
                discriminator:
                  propertyName: name
      operationId: get-comps-id
components:
  schemas:
    CompA:
      title: CompA
      type: object
      discriminator:
        propertyName: name
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    CompB:
      title: CompB
      allOf:
        - $ref: '#/components/schemas/CompA'
        - type: object
          properties:
            testB:
              type: string
    CompC:
      title: CompC
      allOf:
        - $ref: '#/components/schemas/CompB'
        - type: object
          properties:
            testC:
              type: string

CompA
![image](https://user-images.githubusercontent.com/52877209/169280048-0e26f59e-b511-445c-bf6c-3afdabf6f397.png)

CompB extends CompA by one property "testB" which will be added as last property. IMO this is correct.
![image](https://user-images.githubusercontent.com/52877209/169280487-979e2f0b-cd6b-4d30-8d84-10bfc078e5e7.png)

CompC extends now CompB by one property "testC", but this property will now be displayed as first property. Why? And the example on the right side does not change as well.
![image](https://user-images.githubusercontent.com/52877209/169281329-13375ecc-4591-449f-9b04-c0b159ad8558.png)

- Version used: 7.5.19
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by TCDooM** [comment]
so inheritance does work? the Body section is not generate for me when the Body type is a child of inheritance, i worked around it by changing my base type to an interface :(
any idea?

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
