### ISSUE TITLE
Code updates required for new version of fortawesome/free-solid-svg-icons

### ISSUE THREAD

**Issue by dotslashderek** [stoplightio/elements#2168]
The new version - @fortawesome/free-solid-svg-icons": "^6.1.1" -   introduces breaking changes that we'll need to accommodate with code changes - type-check errors after updating to the latest version look like this:

  ../node_modules/@stoplight/mosaic/components/Button/Button.d.ts:15:5
    15     icon?: IIconProps['icon'] | React.ReactElement;
           ~~~~
    The expected type comes from property 'icon' which is declared here on type 'IntrinsicAttributes & Pick<Omit<ButtonProps<"button">, "appearance"> & { placeholder?: string | undefined; appearance?: FieldButtonAppearanceVals | undefined; onClear?: (() => void) | undefined; }, "value" | ... 288 more ... | "onClear"> & RefAttributes<...>'

../packages/elements-core/src/components/TryIt/TryIt.tsx:274:19 - error TS2322: Type 'IconDefinition' is not assignable to type 'IconProp'.

274             <Icon icon={faExclamationTriangle} className="sl-mr-1" />
                      ~~~~

  ../node_modules/@fortawesome/react-fontawesome/index.d.ts:25:3
    25   icon: IconProp
         ~~~~
    The expected type comes from property 'icon' which is declared here on type 'IntrinsicAttributes & IIconProps'

**Comment by mnaumanali94** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Team-DnC-61f945bb2ae66f0010ca5eca/issues/stoplightio/elements/2168?planning-poker) with ZenHub @Amjcraft @kaylachun @mallachari @mmiask @Nezteb @dotslashderek

**Comment by dotslashderek** [comment]
Looking into this further, the issue is actually that we're importing types from @stoplight/mosaic (still on version 5) and also directly importing free-solid-svg-icons in elements (trying to update to version 6) - then using the two together when they're no longer compatible:

`
import { faExclamationCircle, faEye } from '@fortawesome/free-solid-svg-icons';
import { Badge, Tooltip } from '@stoplight/mosaic';
import React from 'react';

import { badgeDefaultBackgroundColor, badgeDefaultColor } from '../../../constants';

export const DeprecatedBadge: React.FC = () => (
  <Tooltip
    renderTrigger={
      <Badge intent="warning" icon={faExclamationCircle} data-testid="badge-deprecated">
        Deprecated
      </Badge>
    }
  >
    This operation has been marked as deprecated, which means it could be removed at some point in the future.
  </Tooltip>
);
`

We also get versions 5 of free-solid-svg-icons indirectly via imports of markdown-viewer and json-schema-viewer.  As there isn't a pressing reason to update Elements to the new version other than depfu bot, my suggestion is to supress auto-updating of this package via depfu until the other packages have also updated.
