### ISSUE TITLE
Schemas shows nullable properties as non-nullable

### ISSUE THREAD

**Issue by Pum-purum** [stoplightio/elements#2170]
Short screenshot: https://disk.yandex.ru/i/aG-XSyaLjF3SGA

**Comment by Amjcraft** [comment]
![Screen Shot 2022-06-29 at 9.24.40 AM.png](https://images.zenhubusercontent.com/60183c1781aef3f13cf126f1/1a23f94b-07d4-43e1-a188-5c05b1482724)

![Screen Shot 2022-06-29 at 9.13.18 AM.png](https://images.zenhubusercontent.com/60183c1781aef3f13cf126f1/2d43bc5b-8d55-4d48-a86e-2ef732e39575)

**As Inline Ref**
![Screen Shot 2022-06-29 at 9.12.17 AM.png](https://images.zenhubusercontent.com/60183c1781aef3f13cf126f1/1fa11cbb-2cd7-43a1-9b24-834f22a5b0fd)

**Comment by Amjcraft** [comment]
@[Андрей](https://github.com/Pum-purum)

**Comment by Pum-purum** [comment]
@Amjcraft sorry, but I can't. Seems like bug is already fixed. Now my endpoint looks like this: https://disk.yandex.ru/i/xIcJ3KzVntkA5Q
