### ISSUE TITLE
Heading anchor replace router hash when `router=hash`

### ISSUE THREAD

**Issue by Airkro** [stoplightio/elements#2176]
## Current Behavior

![1655262182067](https://user-images.githubusercontent.com/12206891/173727866-e74c0890-5a05-4e89-8860-1e164ee3912a.png)

## Steps to Reproduce

1. open <https://elements-demo.stoplight.io/>
2. go to one of ENDPOINTS
3. click an anchor link

## Environment

- Version used: 7.5.20
- Link to your environment/workspace/project: https://elements-demo.stoplight.io/

**Comment by mnaumanali94** [comment]
This is an issue with the demo site. Lets fix that.

**Comment by Airkro** [comment]
Not only in the demo site, but it also happens in my case.

**Comment by danmichaelo** [comment]
Seems like it's fixed in the latest version 🎉 

Here's a test: https://danmichaelo.github.io/stoplight-routing-test/#/operations/get-works#Responses
