### ISSUE TITLE
Resolving links and urls

### ISSUE THREAD

**Issue by caitlinnew** [stoplightio/elements#2205]
We are integrating with Stoplight Elements (https://meta.stoplight.io/docs/elements/ZG9jOjMyNjU4OTY0-elements) and we are having some issues with the links/anchors inside the page. The layout we are using is “sidebar”, the router is “hash”. 

## Current Behavior
The problem is that when I click on a link heading I get redirected on the correct place, but the URL goes to the default one.
The link I’m clicking on - http://127.0.0.1:8887/#gatewayresponse
The link I end up on - http://127.0.0.1:8887/#/

Would you be able to help us resolve this, since with this functionality it’ll be hard for the users to share the specific part of the documentation that is linked to?

## Steps to Reproduce
[6035Bug.zip](https://github.com/stoplightio/elements/files/9190191/6035Bug.zip)

SF 6035

**Comment by pavinduLakshan** [comment]
We are having the same problem and it annoys our end users. A solution to overcome this problem is highly appreciated.

**Comment by lazartsarev** [comment]
Hey, any update on this one?

**Comment by mnaumanali94** [comment]
I can reproduce to it in https://elements-demo.stoplight.io/ 

Verify it works here once the fix is made.
