### ISSUE TITLE
TryIt layout broken in Edge (chromium) browser

### ISSUE THREAD

**Issue by sinowood** [stoplightio/elements#2221]
When body part is long enough to display the scrollbar, body text and selected text (and input cursor) mismatched.

## Current Behavior
![image](https://user-images.githubusercontent.com/1977734/185728752-12289f98-6aaa-4a92-aaef-314a41097d3d.png)

## Possible Workaround/Solution
The problem does not exist in Firefox browser.

## Steps to Reproduce
1. High DPI laptop screen (14.1" 2560x1440)
2. Windows 10, display scaled to 200%, 150% or 100%

## Environment

- Version used: https://unpkg.com/@stoplight/elements@7.6.4/styles.min.css
- Environment name and version (e.g. Chrome 39, node.js 5.4): Microsoft Edge 104.0.1293.63 (64bit)
- Operating System and version (desktop or mobile): Windows 10
- Link to your environment/workspace/project:

**Comment by mnaumanali94** [comment]
Not reproducible in latest edge
