### ISSUE TITLE
Anchor links redirect to a different page when in endpoint definition

### ISSUE THREAD

**Issue by lazartsarev** [stoplightio/elements#2222]
## Context

Trying to go to a anchor link redirects to a dfferent page

## Current Behavior

Trying to go to a anchor link redirects to a dfferent page

## Expected Behavior

Should stay on the same page and update the URL

## Steps to Reproduce

1. Open https://elements-demo.stoplight.io/#/operations/post-todos
2. Go to "Responses" -> "Body" section
3. Click on the anchor link of Body
4. Get redirected to "https://elements-demo.stoplight.io/#/response-body" instead of "https://elements-demo.stoplight.io/#/operations/post-todos/response-body"

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by lazartsarev** [comment]
@mnaumanali94 @P0lip please check this one as well.

**Comment by mnaumanali94** [comment]
@P0lip Didn't we fix this already?

**Comment by P0lip** [comment]
Possibly, although the previous one was a tad different - the URL kept changing, while this one is specifically about scrolling, if I understand it correctly.
We use Mosaic for that scrolling, so perhaps there's some bug in there.
