### ISSUE TITLE
Anchors from headings are not working as expected with hash router

### ISSUE THREAD

**Issue by lazartsarev** [stoplightio/elements#2223]
The anchors are behaving as expected on the overview page when they are for headings.
## Context

Sharing links with anchors to specific part of the page does not work. Clicking on the heading sends me to the top of the page.

## Current Behavior

Opening a URL with anchor for a heading is not scrolling to the correct section
Clicking on a heading is scrolling to the top of the page

## Expected Behavior

Should scroll to the correct position

## Steps to Reproduce

1. Open https://elements-demo.stoplight.io
2. Zoom in so that the lower sections are out of the screen
3. Click on the "cross-origin-resource-sharing" section heading
4. Get scrolled to the top of the page

1. Open https://elements-demo.stoplight.io
2. Zoom in so that the lower sections are out of the screen
3. Copy the link to the "cross-origin-resource-sharing" section heading
4. Open a new tab and paste the link
5. Does not scroll to the anchor

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by lazartsarev** [comment]
@mnaumanali94 @P0lip please take a look at this one as well. Might be related to this change - https://github.com/stoplightio/elements/pull/2220

**Comment by P0lip** [comment]
Yeah, I can indeed reproduce it. Will look into it when I have a minute.
The scroll issue is probably caused by some bug in stoplight/mosaic
