### ISSUE TITLE
Server variable input support

### ISSUE THREAD

**Issue by dahu33** [stoplightio/elements#2236]
## User Story Description

As an API user,

I want to input my server URL,

so I can try the API against the URL of my choice.

---

Currently an API user cannot input a value for a (non enum) [server variable](https://swagger.io/specification/#server-variable-object). Basically only the default or enum values are used.

## Acceptance Criteria
- [ ] User can input the server URL and use it with the Try It functionality.

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by mnaumanali94** [comment]
PR: #2160

**Comment by mnaumanali94** [comment]
Already fixed.
