### ISSUE TITLE
CSS conflicts when adding @stoplight/elements/styles.min.css

### ISSUE THREAD

**Issue by Kirishikesan** [stoplightio/elements#2250]
Elements was integrated with a react webapp and it was observed that the styles from @stoplight/elements/styles.min.css are affecting the styles from the original webapp. Is there any recommended ways of dealing with this.

This is due to generalized tags in the imported stylesheet "@stoplight/elements/styles.min.css"

1. The react webapp without elements

<img width="1512" alt="Screenshot 2022-09-28 at 09 55 59" src="https://user-images.githubusercontent.com/46290313/192688056-e95adf59-af9c-4c6b-8ded-64eb1a16f11d.png">

2. The react webapp after integrating elements

<img width="1512" alt="Screenshot 2022-09-28 at 09 55 14" src="https://user-images.githubusercontent.com/46290313/192687909-8cc9aef1-8914-46b3-ae01-ebbf02cc1575.png">

## Environment
- Version used: @stoplight/elements: ^7.6.4
- Environment name and version: Chrome: 105.0.5195.125
- Operating System and version (desktop or mobile): Mac OS Monterey : V12.6

**Comment by mnaumanali94** [comment]
@Kirishikesan Can we get the source code for this please? It would help us identify the issue.

**Comment by Amjcraft** [comment]
> @Kirishikesan Can we get the source code for this please? It would help us identify the issue.

Or we'll need to do some debugging and  let us know where and what styles are overriding yours

**Comment by Kirishikesan** [comment]
@mnaumanali94 @Amjcraft The source code for this is in the repo [wso2-apim-ui](https://github.com/wso2/apim-apps) which is the UI for an opensource product "WSO2 API Manager".

**Comment by Amjcraft** [comment]
Took a quick look. I'm pretty sure it's the reset.css in mosaic causing this issue.

The [WSO2 comps](https://github.com/wso2/apim-apps/tree/c2735f2a4e4d272a15c693efc85460217e643f78/portals/publisher/src/main/webapp/source/src/app/components/Base/Header/navbar) in question. Implement the the` https://mui.com/material-ui/react-list/ ` Material ui styles appear to use a single selector for css styles. This means the `ol,
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}` inside our reset would override.


I think the best fix would be to scope the mosaic reset.css styles to our `.sl-` styles.

**Comment by shanejonas** [comment]
Running into this same issue where `@stoplight/elements/styles.min.css` is causing a headache in our project since `@stoplight/elements/styles.min.css` pulls in a reset and touches global styles.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
