### ISSUE TITLE
converting OpenAPI Spec to service node using <TryIt> by it's self

### ISSUE THREAD

**Issue by Yahkob** [stoplightio/elements#2259]
It looks like using the main elements component your openapi spec is formatted specifically by `transformOasToServiceNode` but this method is not exposed by elements-core or elements. Maybe I'm missing an easy way to do this conversion. If you're a developer using <TryIt> on it's own should you format the openapi spec yourself or would it make sense to expose `transformOasToServiceNode` in some package?

**Comment by Yahkob** [comment]
@mnaumanali94 formatting open api spec to match the data model expected by elements, specifically `<TryIt/>`

For instance the spec in the live demo example takes this from the open api spec
```
"paths": {
    "/todos": {
      "get": {
        "summary": "List Todos",
        "responses": {
          "200": {
            "description": "Returns a list of Todos",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Todos"
                  }
                },
                "examples": {
                  "List of Todos": {
                    "$ref": "#/components/examples/multiple-todos"
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        },
        "operationId": "get-todos",
        "description": "Returns a list of todos\n\n*Markdown is supported in descriptions. Add information here for users to get accustomed to endpoints*",
        "parameters": [
          {
            "$ref": "#/components/parameters/limit"
          }
        ],
        "security": []
      },
     ...
}
```

and formats it to this before passing as a prop to `<TryIt/>`
```
{
    "id": "fb5abca189fcb",
    "method": "get",
    "path": "/todos",
    "tags": [],
    "extensions": {},
    "iid": "get-todos",
    "description": "Returns a list of todos\n\n*Markdown is supported in descriptions. Add information here for users to get accustomed to endpoints*",
    "summary": "List Todos",
    "responses": [...]
}
```

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
