### ISSUE TITLE
Multiple Tags Of The Operation

### ISSUE THREAD

**Issue by porotkin** [stoplightio/elements#2262]
## Context

When the operation contains multiple tags, the user should be able to see the operation under each specified tag in the Table of Contents.

## Current Behavior

The current version does the grouping by the first met tag in an operation:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/34237389/195065685-8072f338-3c3a-459d-b7b6-cf814b81fbdb.png">

## Expected Behavior

According to SwaggerHub, the expected behavior should look like in the picture below:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/34237389/195065121-e8b4c25a-00ab-4929-a302-73ecf54e47ae.png">

## Possible Solution(s)

Synchronize the logic with SwaggerHub by showing the Operation inside the each mentioned tag in the TOC.

**Comment by teluren** [comment]
Hi, @mnaumanali94, colleagues.
Is there any update on this feature?

**Comment by tomasvalentaopenbean** [comment]
+1 to have this feature worked on
