### ISSUE TITLE
Images no longer display when using Elements and a public github repo

### ISSUE THREAD

**Issue by caitlinnew** [stoplightio/elements#2272]
## Current Behavior
Images hosted on a public github repo no longer display when viewing the project using the stoplight elements widget. They do display when viewing the hosted version.
It appears that the src field is pointing to the wrong URL.

## Expected Behavior
Images should display consistently

## Steps to Reproduce
View the hosted version of a markdown page and notice that the images correctly display.

View the elements version of the page and you will notice that there are no images displayed.

If you inspect the source of both pages you will notice that the hosted version has

`<img src="blob:https://example.stoplight.io/27af8e99-a648-49da-9a5b-5e4b8517e341" alt="" class="sl-image sl-overflow-x-hidden sl-overflow-y-hidden sl-mx-auto sl-bg-canvas-pure sl-border-body">`

while the elements version has

`<img src="https://stoplight.io/api/v1/projects/cHJqODI5/branches/YnI6MTUwMDE1/images/%2Fdocs%2FGuides%2FAutomate%example.png" alt="" class="sl-image sl-overflow-x-hidden sl-overflow-y-hidden sl-mx-auto sl-bg-canvas-pure sl-border-body">`

fetching the image URL https://stoplight.io/api/v1/projects/cHJqOjODI5/branches/YnI6MTUwMDE1/images/%2Fdocs%2FGuides%2FAutomate%example.png

returns a JSON document instead of the expected png image.

**Comment by wmhilton** [comment]
Well... It's not pointing to the "wrong" url per se, just a new one that only returns JSON because we weren't thinking clearly. We'll make it return an image!
