### ISSUE TITLE
Servers Select menu displaying the API Description title instead of server in ReactJS

### ISSUE THREAD

**Issue by cknight2018** [stoplightio/elements#2273]
If I use run this code:
`import React from 'react';
import { API } from '@stoplight/elements';
import '@stoplight/elements/styles.min.css';

export default function Api() {

    const test_swagger = {
        openapi: '3.1.0',
        info: {
            title: 'Some Awesome API',
            version: '1.0.0'
        },
        paths: {
            "/": {
                "post": {
                    "summary": "Summary",
                    "description": "Description",
                },
            }
        },
        servers: [
            {
                "url": "https://server1url.com",
                "description": "server1"
            },
            {
                "url": "https://server2url.com",
                "description": "server2"
            },
            {
                "url": "https://server3url.com",
                "description": "server3"
            }
        ],
    }

    return (
                 <div style={{ height: "100vh" }}>
                        <API
                            basePath={location}
                            apiDescriptionDocument={test_swagger} //swagger
                        />
                        <script>

                        </script>

                    </div>
           
        </div>
    );
}`

The expected result is this: 
![image](https://user-images.githubusercontent.com/35661370/198718352-81931e4e-0a7d-4714-b523-861aef2f6cca.png)

But the actual result is this: 
![image](https://user-images.githubusercontent.com/35661370/198718469-8d6c6d9f-0bb2-42f9-bb5a-de95d48b0df3.png)

## Context
Developers using ReactJS do not see the servers and URLs on the try it out tab.

## Current Behavior
The servers select menu displays the API_Description.info.title instead of the server descriptions

## Expected Behavior
The servers select menu should display the server URLs and descriptions

## Possible Workaround/Solution
Removing the .info.title will display the servers menu properly, but the title will appear as "no-title" because it is removed.

## Steps to Reproduce
Listed Above

## Environment
package.json:
`"dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@meilisearch/instant-meilisearch": "^0.9.0",
    "@mui/icons-material": "^5.10.9",
    "@mui/material": "^5.10.11",
    "@stoplight/elements": "^7.5.12",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "buffer": "^6.0.3",
    "css-loader": "^6.7.1",
    "instantsearch.css": "^7.4.5",
    "postcss-loader": "^7.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-helmet": "^6.1.0",
    "react-instantsearch-dom": "^6.38.0",
    "react-query": "^3.39.2",
    "react-router-dom": "5.3.4",
    "react-scripts": "4.0.0",
    "stream": "^0.0.2",
    "style-loader": "^3.3.1",
    "tiny-invariant": "^1.3.1",
    "url": "^0.11.0",
    "web-vitals": "^2.1.4"
  }`

**Comment by falsaffa** [comment]
@cknight2018 I used the OpenAPI spec you provided and it seems like the issue has been resolved as of the latest version of Elements. I'll leave this issue open for a few more days so that you can confirm.


![Screenshot 2023-07-06 at 9 07 45 AM](https://github.com/stoplightio/elements/assets/44938179/408215f2-5737-414a-8795-8a5585b0a944)
