### ISSUE TITLE
Incorrect request presentation for PHP/guzzle sample

### ISSUE THREAD

**Issue by progotman** [stoplightio/elements#2282]
## Context

Incorrect request presentation for PHP/guzzle sample.

## Current Behavior

Request sample PHP/guzzle presents PHP/cURL sample.

## Expected Behavior

Request sample PHP/guzzle presents PHP/guzzle sample.

## Steps to Reproduce

1. Go to [demo page](https://elements-demo.stoplight.io/)
2. Select any entrypoint
3. Chooce request sample: PHP/guzzle

## Environment

- Version used: 7.7.5
- Environment name and version: Chrome 105+
- Operating System and version: desktop, Linux Mint

**Comment by tetraset** [comment]
I have the same problem. @lottamus could you help us with it?

**Comment by mnaumanali94** [comment]
Hey! This certainly seems to be a bug. Would you mind creating a PR to fix this? The Stoplight team would be happy to help if you have any questions.
