### ISSUE TITLE
Using stoplight elements dev portal with hash router throws a not found

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#2323]
As a user using the hash router I get a 404 when using the secondary Nav on the right side. 

Note: this works fine with elements but not the dev portal

## Environment
Latest dev portal

**Comment by lewis-benson-tbol** [comment]
I am also seeing the same issue when working with Stoplight Elements Dev Portal - clicking the secondary navigation bar on the right hand side is replacing the stoplight ID and tag, rather than adding a # onto the end.
