### ISSUE TITLE
Cant run Elements locally

### ISSUE THREAD

**Issue by andrewgkew** [stoplightio/elements#2334]
I am trying to run elements locally to look at customizing it. Following the steps outlined here: https://github.com/stoplightio/elements/blob/main/CONTRIBUTING.md

I get an issue when running the demo, a blank page in Chrome with an error in the console

```
Uncaught Error: Cannot find module '~/elements/node_modules/webpack-dev-server/client/clients/SockJSClient.js'
```

## Context

I am trying to just spin elements up locally but not able to get it to work and get a blank page with a JS error in the console

## Current Behavior

Opening up http://localhost:4025/ I get a blank page

## Expected Behavior

Opening up http://localhost:4025/ should give me the swagger UI

## Steps to Reproduce

1. git clone https://github.com/stoplightio/elements.git
2. cd elements
3. yarn
4. cd demo
5. yarn start

## Environment

- Version used: lastest master
- Environment name and version (e.g. Chrome 39, node.js 5.4): node v16.19.0 npm 8.19.3 chrome 108.0.5359.98 (Official Build) (arm64)
- Operating System and version (desktop or mobile): MacOS 13.0.1
- Link to your environment/workspace/project:

**Comment by andrewgkew** [comment]
@mnaumanali94 can you help with the above please?

**Comment by andrewgkew** [comment]
Thanks @zhanglianxin this exactly fixed my issue. Shouldnt this then be either part of the project or docs at least?

**Comment by zhanglianxin** [comment]
> @zhanglianxin how am I able to package this up into web web-components.min.js file if I have made some custom changes to the UI? I tried a yarn build (which passes) but no output?

Could you give some more details?

In my case, just in the demo project directory, follow the scripts in `package.json`, exec `yarn build` command, there will be a **dist** folder produced.

**Comment by andrewgkew** [comment]
@zhanglianxin thanks for this, so just to be clear I follow the following process

cd demo
yarn build
cd dist/js 

There is a bundled.min.js file and that file can be used against any API normally as if I was getting the js from spotlight

https://unpkg.com/@stoplight/elements/web-components.min.js

Is that correct?

**Comment by andrewgkew** [comment]
Just tried that and it doesnt work

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/2614141/226410292-8c7d4a0e-62e9-41ff-a580-2ef3148af4a1.png">

**Comment by zhanglianxin** [comment]
> @zhanglianxin thanks for this, so just to be clear I follow the following process
> 
> cd demo yarn build cd dist/js
> 
> There is a bundled.min.js file and that file can be used against any API normally as if I was getting the js from spotlight
> 
> https://unpkg.com/@stoplight/elements/web-components.min.js
> 
> Is that correct?

The `@stoplight/elements` has been imported as one of dependencies into the demo project.

If you just wanna a custom demo application project, the `web-components.min.js` is no needed in webpack-build style may I guess.

If you want to modify the `elements` source project itself, sorry, I cannot help more.

**Comment by andrewgkew** [comment]
@zhanglianxin thanks for your help, I guess what I am trying to understand and to make sure I am clear with what you are saying this is what I am trying to do:

1. Checkout the elements repo
2. Make some custom changes to the layout of the swaggerUI
3. Bundle the changes into a js file
4. Use this on my developer portal

Are you saying that is not possible? Thanks

**Comment by zhanglianxin** [comment]
No, I'm not.

Your motivation is very clear, by the way, do you know how to serve with the `dist` folder?

**Comment by andrewgkew** [comment]
@zhanglianxin no i think thats the part i am missing. After building in demo directory how do i take the dist directory and add that to my own portal.

**Comment by andrewgkew** [comment]
@zhanglianxin if you can detail for me how i take the github repo check it out build it and then use the output of that build in my local project that would be great, if you can give step by step then I can follow that and try get it to work. Thank you :)

**Comment by zhanglianxin** [comment]
> @zhanglianxin no i think thats the part i am missing. After building in demo directory how do i take the dist directory and add that to my own portal.

Just use the `dist` folder as your Web server root, or put all under the `dist` folder into your server root.

Like as in Python:

```bash
cd dist
python3 -m http.server
# then open browser, visit http://localhost:8000/
```

**Comment by andrewgkew** [comment]
@zhanglianxin I am able to run the demo using yarn start (web server) but if I want to take the js and add it to a dev portal I have already do I just need to include everything in that dist folder in my header block?

**Comment by zhanglianxin** [comment]
> @zhanglianxin I am able to run the demo using yarn start (web server) but if I want to take the js and add it to a dev portal I have already do I just need to include everything in that dist folder in my header block?

In theory that is, but depends on your own dev portal. Make sure you have the DOM element with id named 'root' in the html, because of all bundled files serve with the Line#18 `document.getElementById('root')` in `demo/src/index.tsx`.

**Comment by andrewgkew** [comment]
thanks @zhanglianxin this makes sense and looking at the index.html in the dist folder you are right the js and css files are all that are needed, but when this is shown its in the demo style with header at the top to choose any api

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/2614141/226930600-07bb33ff-0682-4415-962f-4066f3edd157.png">

When you use elements from the publishes version you rather specify the API to display is this possible using this demo version of elements? Where in js I can configure the API to display rather than adding the logic for the user to choose and removing the header really

**Comment by zhanglianxin** [comment]
> thanks @zhanglianxin this makes sense and looking at the index.html in the dist folder you are right the js and css files are all that are needed, but when this is shown its in the demo style with header at the top to choose any api
> 
> <img alt="image" width="1630" src="https://user-images.githubusercontent.com/2614141/226930600-07bb33ff-0682-4415-962f-4066f3edd157.png">
> 
> When you use elements from the publishes version you rather specify the API to display is this possible using this demo version of elements? Where in js I can configure the API to display rather than adding the logic for the user to choose and removing the header really

You can specific your own OpenAPI document files in the `demo/src/constants.ts` file.

**Comment by andrewgkew** [comment]
@zhanglianxin thanks for your advice, issue is this is still running elements using the demo app with the API picker at the top of the page.

What I am after is how do I package up elements so that I just get the web-components portion of the project, the same as if I embedded elements as per the docs: https://github.com/stoplightio/elements#web-component

Is there no way of doing that? Cant understand why I am not able to just build the project the same way as stoplight produce the opensource project to users to use?

**Comment by andrewgkew** [comment]
I effectively want to embedded it as follows

`
<div id="stoplight-wrapper">
  <elements-api apiDescriptionDocument="{{ page.body }}" router="hash" />
 </div>
`

**Comment by EdVinyard** [comment]
@andrewgkew , our team has recently taken over maintaining this repository.  Did you accomplish what you were asking about here?  Based on your experience, how can we improve the documentation regarding contributing to the project?

**Comment by chohmann** [comment]
Closing. Please open a new issue if this is still a problem.

**Comment by andrewgkew** [comment]
@EdVinyard I did achieve what I wanted in the end. I am happy to share how I did it if that helps anyone else. PM if you want me to help or point me to the docs and I will kindly create a PR
