### ISSUE TITLE
Elements doesn't work with NextJS out of the box

### ISSUE THREAD

**Issue by angeloanan** [stoplightio/elements#2345]
Using the latest version of Elements with vanilla Nextjs fails compilation with the following error:
```
Failed to compile.

./node_modules/.pnpm/httpsnippet-lite@3.0.3/node_modules/httpsnippet-lite/dist/esm/httpsnippet.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import { Blob, FormData } from 'formdata-node';
| import { formDataIterator, isBlob } from './helpers/form-data.js';
| import { getHeaderName } from './helpers/headers.js';

Import trace for requested module:
./node_modules/.pnpm/httpsnippet-lite@3.0.3/node_modules/httpsnippet-lite/dist/esm/httpsnippet.js
./node_modules/.pnpm/@stoplight+elements-core@7.7.13_react-dom@17.0.2_react@17.0.2/node_modules/@stoplight/elements-core/index.mjs
./node_modules/.pnpm/@stoplight+elements@7.7.13_react-dom@17.0.2_react@17.0.2/node_modules/@stoplight/elements/index.mjs
```

I believe that this is not a duplicate of #2146, #2085 nor #1966. If it is, then its somehow a regression.

## Steps to Reproduce
I've created a quick [demo repository](https://github.com/angeloanan/elements-brokey) which demonstrates the bug.
The repo is a scaffolded **Next 12** app using `create-next-app`. I've added the package to the project and put the component on the `/` page.

1. Clone the repo
2. `yarn install` or `pnpm install`
3. `yarn dev` or `pnpm dev`
4. Navigate to http://localhost:3000

## Environment
I can confirm that the bug is happening on multiple different environment / projects:
- Node 16 - 18
- Next 12 & 13
- Typescript and Vanilla JS
- MacOS / Arch Linux

**Comment by angeloanan** [comment]
The following git patch fixes a mis-configured transitive dependency `httpsnippet-lite`:

```patch
diff --git a/package.json b/package.json
index 53c491562460f631fc47f5af01b899ec3c46d62b..57dce839bb8ab8023210ddc98c476d219464f2fa 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,6 @@
   "homepage": "https://github.com/P0lip/httpsnippet",
   "license": "MIT",
   "sideEffects": false,
-  "type": "commonjs",
   "main": "./dist/cjs/httpsnippet.js",
   "module": "./dist/esm/httpsnippet.js",
   "types": "./dist/types/httpsnippet.d.ts",
```

**Comment by angeloanan** [comment]
As this package uses Web Components, Next complains that the component requires DOM APIs in server-side pre-rendering.

A workaround to this is use Nextjs' Dynamic import as follows:

```ts
import dynamic from "next/dynamic";
const API = dynamic(() => import("@stoplight/elements").then((x) => x.API), { ssr: false });
```

**Comment by P0lip** [comment]
@angeloanan I released a new version of httpsnippet-lite that should address that issue.
LMK if you still experience the issue.
