### ISSUE TITLE
Try-it: Content-type added even when no request body defined

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#2351]
## Context
The bug affects users of Elements with endpoints without a request body. When making a request without a request body defined, elements adds a "content-type: application/json" header. This causes Prism to fail in the proxy-mode.

## Current Behavior
Stoplight adds a "content-type: application/json" header on requests that don't have a request body defined.

## Expected Behavior
No "content-type" header should be added if there's no request body defined. Elements should only add the "content-type" header if a request body is present.

## Steps to Reproduce
1. Create a new OpenAPI file in Stoplight Studio with a GET endpoint without a request body.
2. Publish the OpenAPI file.
3. Go to the "Try It" section and view the request sample.
4. Observe that the "content-type: application/json" header is present, even though there is no request body defined.

**Comment by shartman2003** [comment]
Got this from SPS Commerce: "Our teams are well integrated with Stoplight for sending requests to our API, and so rolling out Prism in front of it has been halted for the time being until we can fix either the Prism side or the Stoplight side."

**Comment by shartman2003** [comment]
@mnaumanali94 SPS Commerce is asking for a timeline on this issue.  This is a high priority for them, it is holding up a release of theirs. Can we get this in the next sprint?

**Comment by mnaumanali94** [comment]
@shartman2003 We can get this in the next sprint 🙏🏼

**Comment by travisgosselin** [comment]
> @shartman2003 We can get this in the next sprint 🙏🏼

Much appreciated!
