### ISSUE TITLE
Try It allows to select only one security, even if openapi requires multiple at once

### ISSUE THREAD

**Issue by manycoding** [stoplightio/elements#2357]
## Context
 Global `security` object contains a list of three objects which according to openapi 3.0 specification https://swagger.io/docs/specification/authentication/ means that user should add `clientId` AND `plaidVersion`

```
security:
  - clientId: []
     plaidVersion: []
```

And this one means user can select either, which works.

```
security:
  - clientId: []
  - plaidVersion: []
```

## Current Behavior
I can select only one of apikeys in Try It

## Expected Behavior
Follow openapi standard https://swagger.io/docs/specification/authentication/

## Possible Workaround/Solution
As a workaround I have to use in-header parameters which is not OpenAPI recommendation.

## Steps to Reproduce

1. Import schema below and navigate to Try It
2. Observe that ApiKey selector is limited to one

## Environment
Just current https://testveryfi.stoplight.io/studio in Chrome 112

```
openapi: 3.0.0
info:
  contact:
    name: Plaid Developer Team
    url: 'https://plaid.com'
  description: 'The Plaid REST API. Please see https://plaid.com/docs/api for more details.'
  termsOfService: 'https://plaid.com/legal/'
  title: The Plaid API
  version: 1.0.0
security:
  - clientId: []
    plaidVersion: []
    secret: []
tags:
  - description: The Plaid API
    name: plaid
paths:
  /accounts/balance/get:
    post:
      operationId: accountsBalanceGet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    clientId:
      in: header
      name: PLAID-CLIENT-ID
      type: apiKey
    plaidVersion:
      in: header
      name: Plaid-Version
      type: apiKey

**Comment by manycoding** [comment]
Same issue https://github.com/stoplightio/elements/issues/2023

**Comment by falsaffa** [comment]
@manycoding closing this issue as a duplicate of #2023.
