### ISSUE TITLE
UI for sending API request where authentication is optional

### ISSUE THREAD

**Issue by tupelo-schneck** [stoplightio/elements#2361]
The OpenAPI specification says about `security` "To make security optional, an empty security requirement ({}) can be included in the array."

We have some API calls where authentication is optional:

      security:
        - {}
        - basicAuth: []
        - bearerAuth: []
        
Our UI with Stoplight, however, doesn't show any indication that authentication is optional, and I can't see any way to "Send API Request" from the Stoplight UI without including either Basic auth or Bearer auth.

**Comment by kentbulza** [comment]
I see an optional info box. So I don't think this comment is correct as of current build? 

Separate *related* issue, which is an OpenAPI gap, not an Elements gap, is that there's no way to say one authentication method is required with ANOTHER optional (e.g. -- if you WANT to add mutualTLS for extra security you can, but at least type "x" is required). Would Stoplight consider adding an x-stoplight element to support this?

**Comment by tupelo-schneck** [comment]
I confirm that as of stoplight/elements 8.0.1 this seems to be working as desired.
