### ISSUE TITLE
Server Variable support in 'Try It' Section

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#2386]
### **Description of Work**
Allow users to dynamically adjust server variables within the 'Try It' section of the documentation. 

### **User Story**
As a user, I want to be able to change server variables within the 'Try It' section, so that I can see and interact with adjusted server URLs and example code samples based on different variable values.

### **Requirements**

- [ ] Introduce input fields for each server variable within the 'Try It' section:
  - These fields should be located above the Parameters section.
  - Each input field should be labeled with the server variable's name.
  - The input fields should change if the server is changed
  

- [ ] Dynamic URL and code sample adjustment:
  - Modifying the value within the server variable input field should automatically update the displayed URL and the example code samples in real-time.
  - The default value for each server variable should be pre-filled in the input field when the 'Try It' section is accessed.

- [ ] Handle server variables with enums:
  - If a server variable has defined allowed values, replace its input field with a dropdown list containing the allowed values.
  - The dropdown should have the default value already selected upon accessing the 'Try It' section.

### **Documentation**
- Not needed

### **Design**
- [ ] This work needs to be reviewed by the Design Team. Add them to the PR as reviewers.

### **Test Plan**
- Ensure server variables can be modified in the 'Try It' section and that they reflect correctly in the URL and example curl command.
- Confirm the behavior of server variables with defined enums in the 'Try It' section.

- [ ] Update existing tests

### **Monitoring & Metrics**
- Not needed

**Comment by mnaumanali94** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Tequila-Mockingbirds-61f945bb2ae66f0010ca5eca/issues/stoplightio/elements/2386?planning-poker) with Zenhub @Amjcraft @billiegoose @cjlanzo @dotslashderek @matty-v @P0lip

**Comment by billiegoose** [comment]
Alright, I yalced it into platform-internal and it looks good.

I'll bump the versions and release it
