### ISSUE TITLE
Server variables in incorrect order

### ISSUE THREAD

**Issue by siimsoni** [stoplightio/elements#2399]
## Context
The template for endpoint URL, shown below the endpoint name, is garbled.

## Current Behavior
The order of server variables is reversed, and the opening brace for the first variable has become another closing brace for the first variable.

## Expected Behavior
The endpoint URL template should be rendered correctly.

## Possible Workaround/Solution
For some reason, part of the server variables is set to RTL. The problem disappears for me as a LTR language user when setting it to LTR.

```
<div class="sl-flex sl-overflow-x-hidden sl-text-lg sl-select-all">
  <div dir="rtl" class="sl-overflow-x-hidden sl-truncate sl-text-muted">
    /{a}/{b<span dir="ltr" style="unicode-bidi: bidi-override;">}</span>
  </div>
  <div class="sl-flex-1 sl-font-semibold">/{clientid}</div
</div>
```

## Steps to Reproduce
```
{
    "openapi": "3.1.0",
    "info": {
        "title": "Schema",
        "version": "",
        "description": "Stoplight Elements test\n",
        "license": {
            "name": "Test",
            "url": "http:\/\/test"
        }
    },
    "servers": [
        {
            "url": "\/{a}\/{b}",
            "variables": {
                "a": {
                    "default": "default_a"
                },
                "b": {
                    "default": "default_b"
                }
            }
        }
    ],
    "paths": {
        "\/{param}": {
            "get": {
                "summary": "feed\/1",
                "description": "Best feed",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "param",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "number",
                            "minimum": 0
                        }
                    }
                ]
            }
        }
    }
}
```

## Environment
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Fishnet Feeds Specification</title>
    <!-- needed for adaptive design -->
    <script
        src="https://unpkg.com/@stoplight/elements@7.10.0/web-components.min.js"
        integrity="sha384-AdF0Ptsg5XBgbc+LIWxukamk4UOVFuaJeTXr8n3PzTe7fu6HdX8lizpOV0IKYxhy"
        crossorigin="anonymous"
    ></script>
    <link
        rel="stylesheet"
        href="https://unpkg.com/@stoplight/elements@7.10.0/styles.min.css"
        integrity="sha384-1lLf7J28IOR7k5RlItk6Y+G3hDgVB3y4RCgWNq6ZSwjYfvJXPtZAdW0uklsAZbGW"
        crossorigin="anonymous"
    />
</head>
<body style="height: 100vh;">
    <elements-api
        apiDescriptionUrl="..."
        router="hash" />
</body>
</html>

```

- Version used: 7.10.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): Google Chrome 116.0.5845.96
- Operating System and version (desktop or mobile): Desktop
- Link to your environment/workspace/project:

**Comment by siimsoni** [comment]
Tested with 7.12.3, still the same problem

**Comment by mnaumanali94** [comment]
<img width="589" alt="Screenshot 2023-10-17 at 6 47 31 PM" src="https://github.com/stoplightio/elements/assets/17899454/bc481c61-27f8-45db-b8ea-7fd81346077b">

How it shows itself

**Comment by dotslashderek** [comment]
Seems to be triggered if the first character is anything but a-zA-Z - will have to look to figure out what we're doing in the code but some quick checking in studio - if the first character of the url is anything other than that, seems to cause the issue with the published docs - 

<img width="570" alt="Screenshot 2023-10-18 at 9 18 35 AM" src="https://github.com/stoplightio/elements/assets/5782229/3d684335-84ec-4adf-b26a-be768bcebdf9">
<img width="337" alt="Screenshot 2023-10-18 at 9 18 43 AM" src="https://github.com/stoplightio/elements/assets/5782229/340c94f5-91f8-48eb-8fb7-e2ec42004914">
<img width="488" alt="Screenshot 2023-10-18 at 9 19 24 AM" src="https://github.com/stoplightio/elements/assets/5782229/c3bf5661-9e14-4f17-9a5a-2b6cdb9aae78">
<img width="482" alt="Screenshot 2023-10-18 at 9 19 31 AM" src="https://github.com/stoplightio/elements/assets/5782229/a974572c-9477-407e-a36a-671dfd217ceb">
<img width="322" alt="Screenshot 2023-10-18 at 9 19 52 AM" src="https://github.com/stoplightio/elements/assets/5782229/48a1a395-ef90-4813-b6e5-9d3701a9be94">
<img width="403" alt="Screenshot 2023-10-18 at 9 20 32 AM" src="https://github.com/stoplightio/elements/assets/5782229/a1dd05ae-6cc8-482b-962a-d7e64ff31297">
<img width="453" alt="Screenshot 2023-10-18 at 9 21 24 AM" src="https://github.com/stoplightio/elements/assets/5782229/55e212a7-7e28-4e27-b46b-c6d8074256bd">
<img width="400" alt="Screenshot 2023-10-18 at 9 22 28 AM" src="https://github.com/stoplightio/elements/assets/5782229/65482a5e-f44e-44d2-a095-e483a636eaf4">
<img width="562" alt="Screenshot 2023-10-18 at 9 23 01 AM" src="https://github.com/stoplightio/elements/assets/5782229/f20b2772-9d5a-4227-b5bc-21f6d6bb96e6">

**Comment by dotslashderek** [comment]
This also shows up in our existing storybook example.  Will add a test for this behavior first:

<img width="736" alt="Screenshot 2023-10-18 at 9 40 48 AM" src="https://github.com/stoplightio/elements/assets/5782229/9c626508-a55b-4243-a37d-d1aa74e6342a">
