### ISSUE TITLE
stacked layout does not show openapi paths

### ISSUE THREAD

**Issue by szczebel** [stoplightio/elements#2415]
## Context
When browsing my API Reference docs, users cannot easily see what is the path of an operation.
They have to go to TryIt->CodeSamples to see the path, which:
- is inconvenient
- will not even be possible if `hideTryIt` is true

## Current Behavior
path not displayed in Docs:
![image](https://github.com/stoplightio/elements/assets/1488353/394033a9-9df4-4456-9709-7ef17b87ee01)

## Expected Behavior
- path should be displayed above the Path Parameters section, before content of `description` from openapi spec

## Possible Workaround/Solution
find path in TryIt section

## Steps to Reproduce
1. open file:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Product Adapter API Reference</title>
    <script src="https://unpkg.com/@stoplight/elements/web-components.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/@stoplight/elements/styles.min.css">
    <style>
      elements-api {
        margin: auto;
        display: block;
        max-width: 600px;
      }
    </style>
</head>
<body>
  <elements-api layout = "stacked" apiDescriptionUrl="https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.0/ghes-3.0.json"></elements-api>
</body>
</html>
```

2. expand whichever operation
3. path is missing:
![image](https://github.com/stoplightio/elements/assets/1488353/37546a1a-4486-45c6-baad-c490c2465ba0)

## Environment

- Version used: https://unpkg.com/@stoplight/elements/web-components.min.js (current as of day of writing)
- Environment name and version (e.g. Chrome 39, node.js 5.4):  Chrome
- Operating System and version (desktop or mobile): Desktop

**Comment by chohmann** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHkzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a75ea7f5a1fb7e13bd8858f30eac53bfce4a655b/image.png)
