### ISSUE TITLE
User story: custom code samples

### ISSUE THREAD

**Issue by rattrayalex** [stoplightio/elements#2453]
## User Story Description
As an API provider who offers SDKs for my API,

I want to include code snippets demonstrating those SDKs for each API request,

so I can make my users integrations much easier.

## Acceptance Criteria

- [ ] Read from a property like `x-codeSamples` in the OAS for each `operation` with something like a hash like `{go: '…', node: '…', python: '…'}` (no opinions here)
- [ ] Display that instead of the default for the given language

## Notes
1. this was originally filed within https://github.com/stoplightio/elements/issues/2175 which was closed as stale
2. This is a feature that [ReadMe.com offers as `x-readme.code-samples`](https://docs.readme.com/main/docs/openapi-extensions#custom-code-samples), and I think Redoc supports as well.

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by weyert** [comment]
@rattrayalex I have been working on a PR to support an initial round of the `x-codeSamples` vendor extension

**Comment by rattrayalex** [comment]
I assume this is now fixed in https://github.com/stoplightio/elements/pull/2574 – thank you @weyert !
