### ISSUE TITLE
Release 7.15.1 (and older ones) not tagged in Git?

### ISSUE THREAD

**Issue by saper** [stoplightio/elements#2455]
As of 2023-11-20 npmjs.org reports 7.15.1 as the newest version, but I cannot find a tag for it in this repository.

**Comment by chohmann** [comment]
The difficulty with tagging in github, is this repository produces 3 different npm packages. They aren't always all released at the same time, so they could be at different versions. So tying that back to 1 github tag is difficult. 

We don't foresee implementing this, so we are going to close this ticket.

**Comment by saper** [comment]
> The difficulty with tagging in github, is this repository produces 3 different npm packages. They aren't always all released at the same time, so they could be at different versions. So tying that back to 1 github tag is difficult.

Thank you! So if I want to reproduce your build from source, which code should I check out?
