### ISSUE TITLE
return type with inheritance is not shown

### ISSUE THREAD

**Issue by TCDooM** [stoplightio/elements#2458]
the ASPNET MVC action method has all the attributes and /// descriptions needed and the return type, response type is not generated in the Docs, it seems to be because the return type has inheritance, if i remove the inheritance or inherent from an interface the docs DO work.
## Context

the Docs just don't show the return/response type

## Current Behavior

no return type is shown in the generated docs (the swagger UI does have the information)

## Expected Behavior

the docs show include the information for the response even if the response has inheritance.

## Possible Workaround/Solution

as i said, i can change my code to NOT have inheritance or change it to an interface instead of a base type... not idle.

## Steps to Reproduce

    <script src="https://unpkg.com/@stoplight/elements@7.13.4/web-components.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/@stoplight/elements@7.13.4/styles.min.css">
...
  <body>
    <elements-api
      apiDescriptionUrl="/swagger/latest/swagger.yaml"
      router="hash"
      hideInternal="true"
      logo="data:image/svg+xml;base64,{LOGO}"
    />
  </body>
...

the "/swagger/latest/swagger.yaml" file has the description for the return types that are not displayed.
## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by chohmann** [comment]
@TCDooM are you asking about the OpenAPI spec that is being generated from your .NET code (For example, via Swashbuckle)? If so, this is not the right place for that question. We really only take over after you have a valid OpenAPI spec generated. 

Or, are you experiencing an issue with how Elements is rendering what you believe to be a valid OpenAPI spec? If so, can you provide the following:
1. The full OpenAPI spec you're trying to render the docs with
2. Example code used to host Elements
3. What elements is rendering
4. what you expect elements to render

**Comment by chohmann** [comment]
@TCDooM since we haven't heard from you, we're going to close this issue. Please reopen when you have the information we requested.
