### ISSUE TITLE
Update to http-spec 7

### ISSUE THREAD

**Issue by mallachari** [stoplightio/elements#2492]
`Http-spec` v7 brings [breaking changes](https://github.com/stoplightio/http-spec/pull/258/files) in oas operation transformation. It introduces webhook operations and changes signature of `transformOas2Operation` and `transformOas3Operation` methods by replacing `path` with `name` and adding `config` object.
Update elements package to use new `http-spec` version.

**Comment by daniel-white** [comment]
this has been released in 8.0.0
