### ISSUE TITLE
toc(oas): malformed path (custom slug)

### ISSUE THREAD

**Issue by andynataco** [stoplightio/elements#2515]
We added a custom slug to our api in the `toc.json` file. 

```json
  {
   "type": "item",
   "title": "Respondent Gateway",
   "uri": "/apis/openapi.yml",
   "slug": "api"
  }
```

The main openapi page has the correct path "baseurl/api". However, the operations and schemas have the following:

- `baseurl/api%2Foperations%2Fcreate-a-create-thing`
- `baseurl/api%2Fschemas%2Ferror`

We're expecting

- `baseurl/api/operations/create-thing`
- `baseurl/api/schemas/error`

## Context

We are forced to use stable ids and cannot use custom slugs to generate legible paths. 

## Current Behavior

The main openapi page has the correct path "baseurl/api". However, the operations and schemes have the following:

- `baseurl/api%2Foperations%2Fcreate-a-create-thing`
- `baseurl/api%2Fschemas%2Ferror`

## Expected Behavior

We're expecting

- `baseurl/api/operations/create-thing`
` `baseurl/api/schemas/error`

## Steps to Reproduce

1. add `slug` to toc api item
2. visit endpoint or schema

**Comment by chohmann** [comment]
We have an internal ticket STOP-47 for our tracking. When we work that ticket, we'll come back and update this ticket.

**Comment by kaylachun** [comment]
Hello @andynataco!  Would we be able to get a bit more information on your use case?  Specifically, are you using elements dev portal and if so, what router are you using (history, memory, hash, static)?  Thank you!

**Comment by brendarearden** [comment]
@andynataco we are going to close this as we are unable to troubleshoot. If you are able to provide more information, feel free to open a new issue with the requested information.

**Comment by andynataco** [comment]
My apologies, I just found some time to check back in. It looks like the issue has been resolved. 

Thank you @kaylachun and @brendarearden! 🙇🏾
