### ISSUE TITLE
$.info.license.name Always Add Word "License"

### ISSUE THREAD

**Issue by kentbulza** [stoplightio/elements#2523]
Elements adds the word "License" to the end of the string contained in $.info.license.name. This make the assumption that every license is an Apache or MIT or something that would always be followed by the word "License", but it may be that the API uses another convention. 

## Context
Would like full control over the License string.

## Current Behavior
Appends the word "License"

## Possible Solution(s)
Simply remove the word "License". If someone wants to append the word "License", they can do so themselves.

**Comment by kentbulza** [comment]
I want to add some more comment to this. The text actually transforms into a URL to [SPDX](https://spdx.org/licenses/). This would be the correct behavior for the `identifier`, which indeed is a SPDX license, but it should not be the behavior for `name`.

**Comment by weyert** [comment]
@kentbulza Can you clarify what you are expecting? Some examples of what you expect to happen on the two scenarios `identifier` and `name` given then I will see if I solve it for you. Got some time from work to work on Elements issues we have ourselves

**Comment by kentbulza** [comment]
Certainly. The spec says EITHER identfier or URL is required. If it IS an
identifier, then that would mean it is an SPDX identifier and then you are
free have the link refer to SPDX. But if identifier is not there, then that
means it's a custom URL (e.g. to a URL on your own website's description of
the license).

In either case, the name (link text) should be simply the text one includes
for the element. Important context is that SPDX does not have the concept
of a commercial license. So for paid APIs that are "all rights reserved",
the ability to describe the license fully by name is important.

As far as backward compatibility, it seems to me only something that has an
identifier might be a candidate for unilaterally adding the word license.
But I would think even that's a stretch -- I'm not sure why, absent words
in the 3.1 spec, one should be adding any words.

**Comment by weyert** [comment]
Don't think we need to query the full name of the SPDX identifier license, right? Just the SPDX identifier itself?

**Comment by weyert** [comment]
Ah that's true. I keep thinking `identifier` relates to `name` but it's `identifier` and/or `url` :)

**Comment by weyert** [comment]
@kentbulza Raised a PR, let me know if this is what you imagined
