### ISSUE TITLE
Supporting tag groups to better organize the list of endpoints in the left rail

### ISSUE THREAD

**Issue by anikitin** [stoplightio/elements#2580]
## User Story Description
As a Stoplight Elements user,
I want to be able to better organize the left-rail table of content for large OpenAPI files.
In order to do it I would like to be able to logically group tags basing on "x-tagGroups" extension in the same or similar way how ReDoc supports it - see https://redocly.com/docs/redoc/redoc-vendor-extensions/#x-taggroups. 
The order of tag groups and tags within a tag group should be exactly followed when building a left rail content in the UI.

##Context
We are playing with Stoplight Elements to visualize large OpenAPI documents with tens or even hundreds of endpoints.
Some Elements features we like better than ReDoc, but the way to define 3-level hierarchy (tagGroup->tag->endpoint) is very important for us.

**Comment by hkosova** [comment]
Already requested here: #1390

**Comment by anikitin** [comment]
@hkosova , thanks, missed that one. So I am closing mine.
