### ISSUE TITLE
If the same endpoint has both POST and GET methods, only one of them can be accessed

### ISSUE THREAD

**Issue by Lhcfl** [stoplightio/elements#2586]
If the same endpoint has both POST and GET methods, only one of them can be accessed

## Context

Example: https://stelpolva.moe/api-doc#/operations/notes/reactions

As shown in the figure, when trying to view notes/reactions, both the GET and POST methods are active, and only the previous POST can be viewed.

![image](https://github.com/stoplightio/elements/assets/41134017/92e2cb70-fc29-4dfd-8c5d-ba723906deca)

## Environment

- Version used: Web Component (https://unpkg.com/@stoplight/elements/web-components.min.js)

**Comment by Lhcfl** [comment]
You can download it here: https://stelpolva.moe/api.json

(Sorry, a few days after this issue was issued, we temporarily switched to Redoc, resulting in the original scene not being visible.)

**Comment by brendarearden** [comment]
@Lhcfl looking at your spec, it appears that the `operationId` is the same for both your POST and GET methods. These should be unique. Could you try making those unique to see if it resolves your issue?

**Comment by Lhcfl** [comment]
Thanks for your help! This is indeed our problem, not following the OpenAPI spec correctly. Then this issue can be closed
