### ISSUE TITLE
Unable to upload file 

### ISSUE THREAD

**Issue by arno-fukuda** [stoplightio/elements#2615]
openapi: 3.0 and openapi: 3.1.0 :

```
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
```
**Stoplight:**
<img width="178" alt="Screenshot 2024-07-23 at 15 06 00" src="https://github.com/user-attachments/assets/51a3c6c6-c2b6-44a3-9c01-739328c7ad9b">

**SwaggerUI**
![Screenshot 2024-07-23 at 15 09 24](https://github.com/user-attachments/assets/6f896acd-e59b-4a18-9c2e-2fb64a5497d9)

**Comment by mdgilene** [comment]
Any update on this. Endpoints with file uploads are completely untestable with elements as opposed to swagger.

**Comment by imniwa** [comment]
i'm facing the same issue.
`in stoplight:`
![image](https://github.com/user-attachments/assets/e0a5c74b-16bc-42e4-aedc-54a4590c52c3)
`in swagger:`
![image](https://github.com/user-attachments/assets/9417e9cd-991e-4e0c-ae3c-6c74f1bdd907)
but i've read at the [documentation](https://docs.stoplight.io/docs/platform/c2f20944173d7-work-with-media-types#from-the-design-editor) 
there's works well 🤷‍♂️ confusing right
![image](https://github.com/user-attachments/assets/cf94dc92-4d4f-4af4-9acf-4e0c93da03d7)

**Comment by lukasikp** [comment]
https://github.com/stoplightio/elements/pull/2737

**Comment by MarcSalvat** [comment]
@lukasikp I think your fix works for application/octet-stream content but it doesn't fix the problem when its multipart/form-data like:

"requestBody": {
  "required": true,
  "content": {
    "multipart/form-data": {
      "schema": {
        "properties": {
          "image": {
            "type": "string",
            "format": "binary",
            "title": "Image"
          }
        },
        "type": "object",
        "required": [
          "image"
        ]
      }
    }
  }
},

This is rendered as an upload button in redoc/swagger too:
![image](https://github.com/user-attachments/assets/fad461c7-b4c1-490b-afa5-6a6383d516fb)
