### ISSUE TITLE
Show/hide "TryIt"

### ISSUE THREAD

**Issue by marbemac** [stoplightio/elements#708]
As an Elements user, I can pass a prop into the API component, and StoplightProject component, so I can hide the "TryIt" component from all HTTP operations.

<p></p>

- Add a property `hideTryIt` to the API and StoplightProject components

- When enabled, we should hide the "TryIt" component

**Comment by mallachari** [comment]
@philsturgeon does hiding TryIt mean hiding whole right panel with request samples and response examples or  should we keep them there?

**Comment by philsturgeon** [comment]
Keep them. Just try it is going away. Some people won’t have a working environment to point to  (CORS drama) or won’t want to use it for other various reasons, but sample code is still good. 

--
Phil Sturgeon
Product @ Stoplight.io

**Comment by mallachari** [comment]
Alright, thanks! Though now I am wondering if it fits to our strategy for using Docs and TryIt component in platform (the issue that is blocked by this one). Our current Docs show operation and TryIt with samples combined. If we hide just TryIt and leave the rest they will be shipped this way to platform which would make adding TryIt painful. Perhaps we could have it this way and add another option of hiding whole right panel so we can easily separate them when needed?
