### ISSUE TITLE
Display API / model version

### ISSUE THREAD

**Issue by marbemac** [stoplightio/elements#782]
As a docs consumer, I can see the API or schema version number in the docs sidebar, so that I can distinguish between two APIs with the same name but different versions.

<p></p>

- Add a light gray version identifier to the right end of the API or Schema file's TableOfContents item

- If the node does not have a version or is v0.0 then don't display the version identifier

<p></p>

![](https://pb-files.s3.amazonaws.com/production/attachments/8b405c50886c1c0e0847c1a2fd36f3b3615dab132d7d25d5e92bd3768c77c7c1/image.png)

<p></p>

**Comment by mpodlasin** [comment]
Calculating version for each API/model should happen on the backend - in elements service.
