### ISSUE TITLE
Generate TypeScript types from queries/reponses

### ISSUE THREAD

**Issue by simoalex** [stoplightio/elements#827]
## User story.

It will be super-useful if Stoplight UI can generate TypeScript types for queries/responses.
Now the nearest thing that you can do - generate JavaScript/Fetch for queries (but not for responses) using the "Try it out" section.
Even worse, I can't just copy-paste it from the generated dock or "Form", because I can't select text with the mouse - somebody restricts that.

## Is your feature request related to a problem?

As I frontend developer a generate a TypeScript type for each query/response, so I need types.
OpenAPI has these types (this is it for), but I can't just copy them.
I think it's pretty easy to add this feature for Stoplight and it will be very useful for front-end coders.

## Describe the solution you'd like

Add types generator for both queries and responses. Or at least let the user select it in docs.
To be sure, I'm not asking to generate .ts/.d.ts files or something like that. Just generate a text { fieldName: type, ... } and that's all.
For example:
type LoginResponse = {     // of even without this line
  id: number;
  email: string;
  first_name: string;
  ....
}

![image](https://user-images.githubusercontent.com/64966695/94524571-75589e00-023b-11eb-95aa-3049ae147a3c.png)

**Comment by philsturgeon** [comment]
We'll leave this to the Roadmap, but there are ways to accomplish this more immediately. E.g: https://www.npmjs.com/package/openapi-typescript
