### ISSUE TITLE
Try It: Add a dropdown for selecting server URL

### ISSUE THREAD

**Issue by marbemac** [stoplightio/elements#830]
As a docs consumer, I can select one of the server URLs defined in the OpenAPI, so I can use Try It to send a request to that base URL.

- If more than one server defined, show a dropdown button on right side of top bar, with an option for each server. Design: <https://www.figma.com/proto/IkNc59AU2JN5Kc1qbd2AiB/Elements?node-id=684%3A8546&viewport=-257%2C522%2C0.43354687094688416&scaling=min-zoom>

- Selecting a server should use it when constructing the request, rendering request samples, etc

- Show the selected server's name as the dropdown label

- Store the selected server in memory so it is used on every request maker for the same API

- If only one server, just show an icon that on hover displays tooltip with server location. Design: <https://www.figma.com/proto/IkNc59AU2JN5Kc1qbd2AiB/Elements?node-id=684%3A8689&viewport=-257%2C522%2C0.43354687094688416&scaling=min-zoom>

**Out of Scope**

Ignore Server Variables for now unless we already have the logic for it.

**Comment by K2ouMais** [comment]
I was about to open an issue for this.

In my docs I have 3 servers, but in the overview it is only showing 1 server.

In the routes/endpoints itself there isnt a way to switch servers.

**Comment by calvinl** [comment]
I have the same issue as @K2ouMais - it only shows the first server on the Overview page.

**Comment by mnaumanali94** [comment]
@noor-ahmad Can we get wires for this too please?
