### ISSUE TITLE
Common Errors Pages

### ISSUE THREAD

**Issue by marbemac** [stoplightio/elements#837]
**User Story**

As somebody potentially new to OpenAPI and giving it a try with a handy CLI/React tool, I would like it to be very forgiving if I open up invalid OpenAPI, completely unknown files, so that I can learn and get more experience with doing OpenAPI correctly.

**Details**

Error pages need to exist for when things go wrong:

- **Unknown File** - When something is not OAS2/3 what do we do? 
 
- **Not found** - when any URL is called that is not an operation, model, article, or something else valid. Note that there's two paths to handle here: 1. The API description document itself cannot be fetched 2. the document could be fetched but the subpath doesn't exist.

**Additional Information**

Currently in API component we are checking for a specific shape of JSON object passed as document to API component:

```ts
  if (isOas3(apiDescriptionDocument)) {
    uriMap = computeOas3UriMap(apiDescriptionDocument);
    documentTags = apiDescriptionDocument.tags?.map(tag => tag.name) || [];
  } else if (isOas2(apiDescriptionDocument)) {
    uriMap = computeOas2UriMap(apiDescriptionDocument);
    documentTags = apiDescriptionDocument.tags?.map(tag => tag.name) || [];
  } else {
    console.error('Document type is unknown');
  }
```

If we are not supporting a given document, we are just bailing out with a `console.error` and a "loading screen":

![Screenshot from 2021-01-05 13-07-43](https://user-images.githubusercontent.com/7916523/103644683-0f289900-4f57-11eb-9190-2469bebcf738.png)

Also, current design quirk, when theres an error the powered by Stoplight shows up at the top of the page.

<img width="1440" alt="Screen Shot 2021-05-06 at 4 49 35 PM" src="https://user-images.githubusercontent.com/67381/117319423-93e6dd80-ae8b-11eb-8851-d55b73dca8dc.png">

**Comment by marcelltoth** [comment]
I believe almost everything asked for here has been covered by previous PRs.

- **Unknown File**: handled just fine, try https://elements-demo.stoplight.io/?spec=https://user-images.githubusercontent.com/67381/114146629-bc70cb80-990f-11eb-8b9c-64c5ae0d6f3b.png#/
- **Not Found**:
  - 1. spec not found: This isn't covered perfectly as it right now falls under the same path as an unknown file, I'll correct it soon.
  - 2. path not found: Impossible. For stacked layout it obviously isn't a possibility, for a sidebar one (and StoplightProject) we redirect to the first ToC item if the current path is not pointing to a valid node.
