### ISSUE TITLE
[spike] Figure out how hard Digest auth is

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/elements#876]
Read all the RFCs, play around with Postman to figure out how many points it takes to do #692, and share results with team.

**Comment by marcelltoth** [comment]
@philsturgeon Why was this closed? There seems to be no intention to drop #692 so this is needed.

**Comment by philsturgeon** [comment]
I’ve added needs info label to digest and I will be doing the work to explain what needs to be done for digest myself.
