### ISSUE TITLE
Finish removing ui-kit from elements

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#957]
We've prioritized a few particularly important ui-kit removing issues, but this is the final cleanup. ui-kit was detected in these files, please make sure its eradicated there and everywhere else.

**packages/elements/src/types.ts** 

- FAIconProp
- ITableOfContentsLink

**packages/elements/src/components/API/APIWithStackedLayout.tsx**

- Collapse
- Icon
- Tab
- Tabs

**packages/elements/src/components/Content/index.tsx**

```
import { SimpleTab, SimpleTabList, SimpleTabPanel, SimpleTabs } from '@stoplight/ui-kit/SimpleTabs';
```

**packages/elements/src/components/Docs/Article/Headings.tsx**

- Button
- Popover
- Position

**packages/elements/src/components/Docs/HttpOperation/Badges.tsx**

- Position
- Tag
- Tooltip

**packages/elements/src/components/Docs/HttpSecuritySchemes/index.tsx**

- Tag

**packages/elements/src/components/Docs/Model/Model.tsx**

- Classes

**packages/elements/src/components/Search/index.tsx**

- Drawer

**packages/elements/src/components/Search/List.tsx**

- Button
- Callout
- Classes
- NonIdealState
- Spinner
- Tag

```
import { ScrollContainer } from '@stoplight/ui-kit/ScrollContainer';
```

**packages/elements/src/components/Search/SearchBar.tsx**

- Button
- FormInput

**packages/elements/src/components/TableOfContents/Row.tsx**

- DefaultRow
- RowComponentType

**packages/elements/src/containers/API.tsx**

- NonIdealState

**packages/elements/src/containers/Docs.tsx**

- NonIdealState

**packages/elements/src/containers/TableOfContents.tsx**

- ITableOfContents
- TableOfContents

Then:

- Remove usage of unprefixed tailwind classnames.

- Remove usage of blueprint components.

- Remove Blueprint icons.

If you can, try and show some statistics of the reduction in bundle size and loaded dependencies in the browser. Everyone likes to see things like this: Sprint Review, could even use some screenshots for Social Media to get people excited about the new version.

**Comment by philsturgeon** [comment]
@marbemac I updated the list to show what UI kit is being used where, and here is the deduped list of components in use. 

- Button
- Callout
- Classes
- Collapse
- DefaultRow
- Drawer
- FAIconProp
- FormInput
- Icon
- ITableOfContents
- ITableOfContentsLink
- NonIdealState
- Popover
- Position
- RowComponentType
- ScrollContainer
- SimpleTab
- SimpleTabList
- SimpleTabPanel
- SimpleTabs
- Spinner
- Tab
- TableOfContents
- Tabs
- Tag
- Tooltip

**Comment by marbemac** [comment]
I highly suggest completing #959 first - there is a lot of leftover code lying around in the repo. Some of the items you listed above are only in use in dead code areas (I only checked a few, unsure how much exactly).

If remove old search code, a lot of the items in the list above go away. On the whole though, Mosaic should be able to handle what's left without a problem.

The only items I can think of that might give an issue is `Tag`, `Spinner`, and `NonIdealState`. The are such trivial components though that I suggest creating equivalent in Elements if Mosaic doesn't have what's needed - can replace in future w Mosaic if those ever make it over.

**Comment by philsturgeon** [comment]
Ok, we'll crack on with this after dead code purge, see how far we can get, and make our own versions of those if we get stuck. Hopefully nothing bigger pops up in the process.
