### ISSUE TITLE
Page hang when navigating to a certain endpoint

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/elements#989]
## Describe the bug

I found an endpoint (`HttpOperation`) to which if you navigate you get a full hang.

## To Reproduce

1. Launch the Elements storybook.
2. Change input project to `public-apis`
3. Navigate to the `StoplightProject` story, then to *Bitbucket API / Get a Repository Diffstat*
3. App hangs.

## Expected behavior

Loads? 😄 

## Additional context

**Screenshots**

![image](https://user-images.githubusercontent.com/543372/113116818-1a195f80-920e-11eb-8505-8000491a6cc3.png)

**Environment (remove any that are not applicable):**
 - Library version: 03f6fe8226ef9eff95
 - OS: Windows 10
 - Browser: Firefox 87
 - Platform: desktop

**Comment by mmiask** [comment]
Reopening, as this emerged again

**Comment by marcelltoth** [comment]
👀 😎
